-- Seed data for the english_vocabulary category in wordup_entities (Exactly 100 words)

INSERT INTO wordup_entities (type, label, metadata, difficulty, tags) VALUES
-- Easy Words (Difficulty 1-2) (32 Words)
('english_vocabulary', 'Benevolent', '{"synonym": "kind", "antonym": "cruel", "definition": "well meaning and kindly"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Fragile', '{"synonym": "delicate", "antonym": "sturdy", "definition": "easily broken or damaged"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Timid', '{"synonym": "shy", "antonym": "bold", "definition": "showing a lack of courage or confidence"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Vast', '{"synonym": "huge", "antonym": "tiny", "definition": "of very great extent or quantity"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Obvious', '{"synonym": "clear", "antonym": "hidden", "definition": "easily perceived or understood"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Generous', '{"synonym": "giving", "antonym": "selfish", "definition": "showing a readiness to give more of something"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Honest', '{"synonym": "truthful", "antonym": "deceitful", "definition": "free of deceit and untruthful"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Hostile', '{"synonym": "unfriendly", "antonym": "friendly", "definition": "showing opposition or dislike"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Ambitious', '{"synonym": "determined", "antonym": "lazy", "definition": "having or showing a strong desire to succeed"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Anxious', '{"synonym": "worried", "antonym": "calm", "definition": "experiencing worry or unease"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Brief', '{"synonym": "short", "antonym": "long", "definition": "of short duration or concise"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Courageous', '{"synonym": "brave", "antonym": "cowardly", "definition": "showing courage or bravery"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Gloomy', '{"synonym": "dark", "antonym": "bright", "definition": "dark or poorly lit, especially so as to appear depressing"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Peculiar', '{"synonym": "strange", "antonym": "normal", "definition": "different to what is normal or expected"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Accurate', '{"synonym": "correct", "antonym": "incorrect", "definition": "free from mistakes or errors"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Clumsy', '{"synonym": "awkward", "antonym": "graceful", "definition": "awkward in movement or in handling things"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Eager', '{"synonym": "enthusiastic", "antonym": "indifferent", "definition": "strongly wanting to do or have something"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Fancy', '{"synonym": "elaborate", "antonym": "plain", "definition": "elaborate in structure or decoration"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Grateful', '{"synonym": "thankful", "antonym": "unthankful", "definition": "feeling or showing appreciation"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Harsh', '{"synonym": "rough", "antonym": "gentle", "definition": "unpleasantly rough or jarring"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Imitate', '{"synonym": "copy", "antonym": "originate", "definition": "copy or simulate"}', 2, ARRAY['easy', 'verbs']),
('english_vocabulary', 'Jealous', '{"synonym": "envious", "antonym": "trusting", "definition": "feeling or showing envy of someone"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Keen', '{"synonym": "sharp", "antonym": "dull", "definition": "having or showing eagerness or enthusiasm"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Loyal', '{"synonym": "faithful", "antonym": "disloyal", "definition": "giving or showing firm and constant support"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Meager', '{"synonym": "scanty", "antonym": "abundant", "definition": "lacking in quantity or quality"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Neglect', '{"synonym": "ignore", "antonym": "cherish", "definition": "fail to care for properly"}', 2, ARRAY['easy', 'verbs']),
('english_vocabulary', 'Praise', '{"synonym": "compliment", "antonym": "criticize", "definition": "express warm approval or admiration"}', 1, ARRAY['easy', 'verbs']),
('english_vocabulary', 'Rapid', '{"synonym": "fast", "antonym": "slow", "definition": "happening in a short time or at a great rate"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Scarce', '{"synonym": "rare", "antonym": "plentiful", "definition": "insufficient for the demand"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Unique', '{"synonym": "distinctive", "antonym": "common", "definition": "being the only one of its kind"}', 1, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Vague', '{"synonym": "unclear", "antonym": "clear", "definition": "of uncertain, indefinite, or unclear character"}', 2, ARRAY['easy', 'adjectives']),
('english_vocabulary', 'Wealthy', '{"synonym": "rich", "antonym": "poor", "definition": "having a great deal of money, resources, or assets"}', 1, ARRAY['easy', 'adjectives']),

-- Medium Words (Difficulty 3) (30 Words)
('english_vocabulary', 'Abundant', '{"synonym": "plentiful", "antonym": "scarce", "definition": "existing or available in large quantities"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Diligent', '{"synonym": "hardworking", "antonym": "lazy", "definition": "having or showing care and conscientiousness"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Exotic', '{"synonym": "foreign", "antonym": "native", "definition": "originating in or characteristic of a distant foreign country"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Gullible', '{"synonym": "naive", "antonym": "skeptical", "definition": "easily persuaded to believe something"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Linger', '{"synonym": "stay", "antonym": "leave", "definition": "stay in a place longer than necessary"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Novice', '{"synonym": "beginner", "antonym": "expert", "definition": "a person new to and inexperienced in a job or situation"}', 3, ARRAY['medium', 'nouns']),
('english_vocabulary', 'Obsolete', '{"synonym": "out-of-date", "antonym": "modern", "definition": "no longer produced or used"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Prosper', '{"synonym": "thrive", "antonym": "fail", "definition": "succeed in material terms"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Reluctance', '{"synonym": "unwillingness", "antonym": "eagerness", "definition": "unwillingness to do something"}', 3, ARRAY['medium', 'nouns']),
('english_vocabulary', 'Tranquil', '{"synonym": "peaceful", "antonym": "chaotic", "definition": "free from disturbance"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Adversity', '{"synonym": "hardship", "antonym": "fortune", "definition": "a state of serious or continued difficulty"}', 3, ARRAY['medium', 'nouns']),
('english_vocabulary', 'Clamor', '{"synonym": "noise", "antonym": "silence", "definition": "a loud and confused noise, especially that of people shouting"}', 3, ARRAY['medium', 'nouns']),
('english_vocabulary', 'Deviate', '{"synonym": "stray", "antonym": "conform", "definition": "depart from an established course"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Emulate', '{"synonym": "imitate", "antonym": "original", "definition": "match or surpass a person or achievement, typically by imitation"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Baffle', '{"synonym": "perplex", "antonym": "clarify", "definition": "totally bewilder or perplex"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Coherent', '{"synonym": "logical", "antonym": "muddled", "definition": "logical and consistent"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Deceit', '{"synonym": "dishonesty", "antonym": "honesty", "definition": "the action or practice of deceiving someone"}', 3, ARRAY['medium', 'nouns']),
('english_vocabulary', 'Eloquent', '{"synonym": "fluent", "antonym": "inarticulate", "definition": "fluent or persuasive in speaking or writing"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Frugal', '{"synonym": "sparing", "antonym": "wasteful", "definition": "sparing or economical with regard to money or food"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Hinder', '{"synonym": "obstruct", "antonym": "help", "definition": "create difficulties for someone, resulting in delay or obstruction"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Inherent', '{"synonym": "innate", "antonym": "acquired", "definition": "existing in something as a permanent, essential, or characteristic attribute"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Jubilant', '{"synonym": "joyful", "antonym": "sorrowful", "definition": "feeling or expressing great happiness and triumph"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Lament', '{"synonym": "mourn", "antonym": "celebrate", "definition": "express passionate grief or sorrow"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Malice', '{"synonym": "hostility", "antonym": "goodwill", "definition": "the intention or desire to do evil"}', 3, ARRAY['medium', 'nouns']),
('english_vocabulary', 'Nurture', '{"synonym": "cherish", "antonym": "neglect", "definition": "care for and encourage the growth or development of"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Obscure', '{"synonym": "hidden", "antonym": "obvious", "definition": "not discovered or known about"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Peril', '{"synonym": "danger", "antonym": "safety", "definition": "serious and immediate danger"}', 3, ARRAY['medium', 'nouns']),
('english_vocabulary', 'Quell', '{"synonym": "suppress", "antonym": "incite", "definition": "put an end to a rebellion or other disorder"}', 3, ARRAY['medium', 'verbs']),
('english_vocabulary', 'Robust', '{"synonym": "strong", "antonym": "weak", "definition": "strong and healthy"}', 3, ARRAY['medium', 'adjectives']),
('english_vocabulary', 'Sovereign', '{"synonym": "supreme", "antonym": "dependent", "definition": "possessing supreme or ultimate power"}', 3, ARRAY['medium', 'nouns']),

-- Hard Words (Difficulty 4-5) (38 Words)
('english_vocabulary', 'Ambiguous', '{"synonym": "unclear", "antonym": "precise", "definition": "open to more than one interpretation"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Cacophony', '{"synonym": "noise", "antonym": "harmony", "definition": "a harsh discordant mixture of sounds"}', 4, ARRAY['hard', 'nouns']),
('english_vocabulary', 'Ephemeral', '{"synonym": "short-lived", "antonym": "permanent", "definition": "lasting for a very short time"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Loquacious', '{"synonym": "talkative", "antonym": "taciturn", "definition": "tending to talk a great deal"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Meticulous', '{"synonym": "careful", "antonym": "careless", "definition": "showing great attention to detail"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Pragmatic', '{"synonym": "practical", "antonym": "idealistic", "definition": "dealing with things sensibly and realistically"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Resilient', '{"synonym": "tough", "antonym": "vulnerable", "definition": "able to withstand or recover quickly from difficult conditions"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Superfluous', '{"synonym": "unnecessary", "antonym": "essential", "definition": "unnecessary, especially through being more than enough"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Venerable', '{"synonym": "respected", "antonym": "disreputable", "definition": "accorded a great deal of respect, especially because of age"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Wary', '{"synonym": "cautious", "antonym": "trusting", "definition": "feeling or showing caution about possible dangers"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Altruistic', '{"synonym": "unselfish", "antonym": "greedy", "definition": "showing concern for the well-being of others"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Capricious', '{"synonym": "fickle", "antonym": "stable", "definition": "given to sudden and unaccountable changes of mood"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Enigmatic', '{"synonym": "mysterious", "antonym": "straightforward", "definition": "difficult to interpret or understand"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Gregarious', '{"synonym": "sociable", "antonym": "introverted", "definition": "fond of company"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Mitigate', '{"synonym": "reduce", "antonym": "aggravate", "definition": "make less severe or painful"}', 5, ARRAY['hard', 'verbs']),
('english_vocabulary', 'Plausible', '{"synonym": "believable", "antonym": "unlikely", "definition": "seeming reasonable or probable"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Scrutinize', '{"synonym": "examine", "antonym": "ignore", "definition": "examine or inspect closely and thoroughly"}', 5, ARRAY['hard', 'verbs']),
('english_vocabulary', 'Ubiquitous', '{"synonym": "omnipresent", "antonym": "rare", "definition": "present, appearing, or found everywhere"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Vociferous', '{"synonym": "outspoken", "antonym": "quiet", "definition": "vehement or clamorous"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Zealous', '{"synonym": "enthusiastic", "antonym": "indifferent", "definition": "having or showing zeal"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Anachronism', '{"synonym": "misplacement", "antonym": "synchronization", "definition": "a thing belonging or appropriate to another period"}', 4, ARRAY['hard', 'nouns']),
('english_vocabulary', 'Belligerent', '{"synonym": "hostile", "antonym": "peaceful", "definition": "hostile and aggressive"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Cognizant', '{"synonym": "aware", "antonym": "ignorant", "definition": "having knowledge or being aware of"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Dearth', '{"synonym": "scarcity", "antonym": "abundance", "definition": "a scarcity or lack of something"}', 4, ARRAY['hard', 'nouns']),
('english_vocabulary', 'Exacerbate', '{"synonym": "worsen", "antonym": "alleviate", "definition": "make a bad situation worse"}', 5, ARRAY['hard', 'verbs']),
('english_vocabulary', 'Fastidious', '{"synonym": "fussy", "antonym": "easygoing", "definition": "very attentive to and concerned about detail"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Incongruous', '{"synonym": "out-of-place", "antonym": "harmonious", "definition": "not in harmony with the surroundings"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Juxtapose', '{"synonym": "contrast", "antonym": "align", "definition": "place close together for contrasting effect"}', 4, ARRAY['hard', 'verbs']),
('english_vocabulary', 'Malevolent', '{"synonym": "hostile", "antonym": "benevolent", "definition": "having or showing a wish to do evil to others"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Nefarious', '{"synonym": "wicked", "antonym": "heroic", "definition": "wicked or criminal"}', 5, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Ostentatious', '{"synonym": "showy", "antonym": "modest", "definition": "characterized by vulgar or pretentious display"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Pervasive', '{"synonym": "widespread", "antonym": "localized", "definition": "spreading widely throughout an area or group"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Rancor', '{"synonym": "resentment", "antonym": "affection", "definition": "bitterness or resentfulness, especially long-standing"}', 4, ARRAY['hard', 'nouns']),
('english_vocabulary', 'Spurious', '{"synonym": "fake", "antonym": "genuine", "definition": "not being what it purports to be"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Taciturn', '{"synonym": "quiet", "antonym": "talkative", "definition": "reserved or uncommunicative in speech"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Vindicate', '{"synonym": "clear", "antonym": "convict", "definition": "clear someone of blame or suspicion"}', 5, ARRAY['hard', 'verbs']),
('english_vocabulary', 'Trivial', '{"synonym": "minor", "antonym": "important", "definition": "of little value or importance"}', 4, ARRAY['hard', 'adjectives']),
('english_vocabulary', 'Verify', '{"synonym": "confirm", "antonym": "disprove", "definition": "make sure that something is true or accurate"}', 4, ARRAY['hard', 'verbs']);
