-- ===================================================================
-- Migration: seed 100 english_fundamentals entities
-- Schema per PROCEDURAL_ENTITY_RULES.md (Class B enriched with
-- English-specific keys used by the edge function generic engine
-- and promptFormatter).
-- ===================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM wordup_entities WHERE type = 'english_fundamentals' LIMIT 1) THEN

        -- ── PARTS OF SPEECH (10) ────────────────────────────────────────
        INSERT INTO wordup_entities (type, label, metadata, difficulty, tags) VALUES
        ('english_fundamentals', 'Noun',
         '{"description":"A word that names a person, place, thing, or idea","category":"Parts of Speech","difficulty":1,"popularity":95,"definition":"A noun is a part of speech that functions as the name of a specific entity — a person, place, thing, or abstract idea.","example":"London, desk, teacher","contrast":"Verb","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Verb',
         '{"description":"A word that expresses an action, occurrence, or state of being","category":"Parts of Speech","difficulty":1,"popularity":95,"definition":"A verb describes what the subject of a sentence does, what happens to it, or its state of existence.","example":"run, write, exist","contrast":"Noun","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Adjective',
         '{"description":"A word that modifies or describes a noun or pronoun","category":"Parts of Speech","difficulty":1,"popularity":90,"definition":"An adjective provides additional information about a noun or pronoun, such as its quality, size, or quantity.","example":"beautiful, quick, silent","contrast":"Adverb","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Adverb',
         '{"description":"A word that modifies a verb, adjective, or another adverb","category":"Parts of Speech","difficulty":2,"popularity":85,"definition":"An adverb adds detail about how, when, where, or to what extent an action occurs or a quality exists.","example":"quickly, very, silently","contrast":"Adjective","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Pronoun',
         '{"description":"A word that stands in for a noun or noun phrase","category":"Parts of Speech","difficulty":1,"popularity":85,"definition":"A pronoun replaces a noun to avoid repetition, referring to a person, thing, or concept already mentioned.","example":"he, she, it, they","contrast":"Noun","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Preposition',
         '{"description":"A word that shows the relationship between a noun and another word","category":"Parts of Speech","difficulty":2,"popularity":80,"definition":"A preposition indicates direction, time, location, or spatial relationships between elements in a sentence.","example":"in, on, at, under, between","contrast":"Conjunction","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Conjunction',
         '{"description":"A word that connects words, phrases, or clauses","category":"Parts of Speech","difficulty":2,"popularity":80,"definition":"A conjunction joins linguistic units of equal or unequal rank to form coherent sentences.","example":"and, but, or, because","contrast":"Preposition","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Interjection',
         '{"description":"A word or phrase that expresses strong emotion or surprise","category":"Parts of Speech","difficulty":1,"popularity":70,"definition":"An interjection is a sudden exclamation that stands alone to convey emotion, greeting, or reaction.","example":"Wow! Ouch! Hey! Oh!","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Article',
         '{"description":"A word that defines a noun as specific or unspecific","category":"Parts of Speech","difficulty":1,"popularity":75,"definition":"An article introduces a noun and indicates whether it refers to a specific instance or a general concept.","example":"a, an, the","contrast":"Determiner","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Determiner',
         '{"description":"A word that introduces and limits a noun in context","category":"Parts of Speech","difficulty":2,"popularity":70,"definition":"A determiner precedes a noun to specify quantity, possession, definiteness, or distribution.","example":"this, that, some, my, each","contrast":"Article","images":[]}',
         2, ARRAY['concept', 'grammar']),

        -- ── TENSES (12) ──────────────────────────────────────────────────
        ('english_fundamentals', 'Simple Present',
         '{"description":"A tense used for habitual actions, general truths, and fixed schedules","category":"Tenses","difficulty":1,"popularity":90,"definition":"The simple present describes actions that are regular, factual, or scheduled — it does not indicate ongoing action.","example":"She walks to school every day.","contrast":"Present Continuous","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Simple Past',
         '{"description":"A tense used for completed actions at a specific time in the past","category":"Tenses","difficulty":1,"popularity":90,"definition":"The simple past expresses an action that began and ended at a definite time in the past.","example":"They visited the museum yesterday.","contrast":"Present Perfect","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Simple Future',
         '{"description":"A tense used for actions that will happen later","category":"Tenses","difficulty":2,"popularity":85,"definition":"The simple future expresses predictions, promises, or spontaneous decisions about events yet to occur.","example":"I will call you tomorrow.","contrast":"Future Continuous","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Present Continuous',
         '{"description":"A tense used for actions happening right now or around the current time","category":"Tenses","difficulty":2,"popularity":85,"definition":"The present continuous describes an ongoing action in progress at the moment of speaking or a temporary situation.","example":"She is reading a book right now.","contrast":"Simple Present","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Past Continuous',
         '{"description":"A tense used for actions that were ongoing at a specific past moment","category":"Tenses","difficulty":2,"popularity":80,"definition":"The past continuous describes an action that was in progress at a particular time in the past, often interrupted by another event.","example":"I was watching TV when the phone rang.","contrast":"Simple Past","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Future Continuous',
         '{"description":"A tense used for actions that will be in progress at a future time","category":"Tenses","difficulty":3,"popularity":75,"definition":"The future continuous describes an action that will be ongoing at a specified future moment.","example":"This time next week, I will be flying to Paris.","contrast":"Simple Future","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Present Perfect',
         '{"description":"A tense linking past actions to the present moment","category":"Tenses","difficulty":3,"popularity":85,"definition":"The present perfect connects a past action or experience to the present, without specifying exactly when it occurred.","example":"She has visited Japan three times.","contrast":"Simple Past","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Past Perfect',
         '{"description":"A tense showing that one past action happened before another","category":"Tenses","difficulty":3,"popularity":80,"definition":"The past perfect indicates an action completed before another past action or time.","example":"They had already eaten when I arrived.","contrast":"Present Perfect","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Future Perfect',
         '{"description":"A tense describing actions that will be completed by a future time","category":"Tenses","difficulty":4,"popularity":70,"definition":"The future perfect expresses an action that will be finished before a specified future moment.","example":"By next month, I will have finished the project.","contrast":"Future Continuous","images":[]}',
         4, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Present Perfect Continuous',
         '{"description":"A tense for actions that started in the past and continue into the present","category":"Tenses","difficulty":4,"popularity":70,"definition":"The present perfect continuous emphasizes the duration of an action that began in the past and is still ongoing.","example":"She has been studying for three hours.","contrast":"Present Perfect","images":[]}',
         4, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Past Perfect Continuous',
         '{"description":"A tense for ongoing past actions that happened before another past event","category":"Tenses","difficulty":4,"popularity":65,"definition":"The past perfect continuous emphasizes the duration of an action that was ongoing before another past event occurred.","example":"They had been waiting for an hour when the bus finally arrived.","contrast":"Past Perfect","images":[]}',
         4, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Future Perfect Continuous',
         '{"description":"A tense for actions that will have been ongoing up to a future point","category":"Tenses","difficulty":5,"popularity":60,"definition":"The future perfect continuous emphasizes the duration of an action that will continue up to a specified future time.","example":"By December, I will have been working here for ten years.","contrast":"Future Perfect","images":[]}',
         5, ARRAY['concept', 'grammar']),

        -- ── GRAMMAR CONCEPTS (14) ───────────────────────────────────────
        ('english_fundamentals', 'Subject',
         '{"description":"The person or thing that performs the action in a sentence","category":"Grammar","difficulty":1,"popularity":90,"definition":"The subject is the noun or pronoun that performs the verb or is described by the sentence.","example":"The cat sat on the mat.","contrast":"Object","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Predicate',
         '{"description":"The part of a sentence that tells what the subject does or is","category":"Grammar","difficulty":2,"popularity":80,"definition":"The predicate contains the verb and all additional information about what the subject does or what happens to it.","example":"In ''Birds fly'', the predicate is ''fly''.","contrast":"Subject","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Object',
         '{"description":"The person or thing that receives the action of the verb","category":"Grammar","difficulty":2,"popularity":80,"definition":"An object is a noun or pronoun that is acted upon by the subject via the verb — it receives the action.","example":"She threw the ball.","contrast":"Subject","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Clause',
         '{"description":"A group of words containing a subject and a predicate","category":"Grammar","difficulty":2,"popularity":75,"definition":"A clause is a grammatical unit with its own subject and verb; it may be independent or dependent.","example":"Although it rained, we still went out.","contrast":"Phrase","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Phrase',
         '{"description":"A group of words that functions as a unit without a subject-verb pair","category":"Grammar","difficulty":2,"popularity":75,"definition":"A phrase is a meaningful group of words that lacks a subject and verb combination.","example":"under the bed, walking home","contrast":"Clause","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Subject-Verb Agreement',
         '{"description":"The grammatical rule that the subject and verb must match in number","category":"Grammar","difficulty":3,"popularity":85,"definition":"Subject-verb agreement requires a singular subject to take a singular verb and a plural subject to take a plural verb.","example":"She runs fast. They run fast.","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Active Voice',
         '{"description":"A sentence structure where the subject performs the action","category":"Grammar","difficulty":2,"popularity":80,"definition":"In active voice, the subject acts upon the object, creating a direct and vigorous sentence.","example":"The chef cooked the meal.","contrast":"Passive Voice","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Passive Voice',
         '{"description":"A sentence structure where the subject receives the action","category":"Grammar","difficulty":3,"popularity":80,"definition":"In passive voice, the object of an action becomes the subject, and the verb phrase includes a form of ''be'' plus past participle.","example":"The meal was cooked by the chef.","contrast":"Active Voice","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Direct Speech',
         '{"description":"The exact words spoken by someone, enclosed in quotation marks","category":"Grammar","difficulty":2,"popularity":75,"definition":"Direct speech quotes a person''s exact words verbatim within quotation marks.","example":"She said, ''I am tired.''","contrast":"Reported Speech","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Reported Speech',
         '{"description":"A way of conveying what someone said without quoting them exactly","category":"Grammar","difficulty":3,"popularity":75,"definition":"Reported speech (indirect speech) paraphrases what someone said, often shifting tenses and pronouns.","example":"She said that she was tired.","contrast":"Direct Speech","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Conditional Type 0',
         '{"description":"A conditional expressing general truths or scientific facts","category":"Grammar","difficulty":3,"popularity":70,"definition":"Type 0 conditional uses present tense in both clauses for statements that are always true.","example":"If you heat ice, it melts.","contrast":"Conditional Type 1","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Conditional Type 1',
         '{"description":"A conditional expressing a real possibility in the future","category":"Grammar","difficulty":3,"popularity":75,"definition":"Type 1 conditional uses present tense in the if-clause and will + base verb in the main clause for likely future outcomes.","example":"If it rains, I will stay home.","contrast":"Conditional Type 2","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Conditional Type 2',
         '{"description":"A conditional expressing an unreal or hypothetical present situation","category":"Grammar","difficulty":4,"popularity":70,"definition":"Type 2 conditional uses past tense in the if-clause and would + base verb in the main clause for imaginary scenarios.","example":"If I had a million dollars, I would travel the world.","contrast":"Conditional Type 1","images":[]}',
         4, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Conditional Type 3',
         '{"description":"A conditional expressing an unreal past situation and its imagined result","category":"Grammar","difficulty":4,"popularity":65,"definition":"Type 3 conditional uses past perfect in the if-clause and would have + past participle in the main clause for impossible past scenarios.","example":"If I had studied harder, I would have passed the exam.","contrast":"Conditional Type 2","images":[]}',
         4, ARRAY['concept', 'grammar']),

        -- ── PUNCTUATION (10) ─────────────────────────────────────────────
        ('english_fundamentals', 'Period',
         '{"description":"A punctuation mark used to end a declarative sentence","category":"Punctuation","difficulty":1,"popularity":90,"definition":"The period (full stop) indicates the end of a declarative or imperative sentence.","example":"I enjoy reading.","contrast":"Comma","images":[]}',
         1, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Comma',
         '{"description":"A punctuation mark indicating a slight pause or separation of elements","category":"Punctuation","difficulty":2,"popularity":85,"definition":"The comma separates items in a list, clauses, or parenthetical elements within a sentence.","example":"apples, oranges, and bananas","contrast":"Semicolon","images":[]}',
         2, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Question Mark',
         '{"description":"A punctuation mark used at the end of an interrogative sentence","category":"Punctuation","difficulty":1,"popularity":90,"definition":"The question mark replaces the period at the end of a direct question.","example":"Where are you going?","contrast":"Exclamation Mark","images":[]}',
         1, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Exclamation Mark',
         '{"description":"A punctuation mark used to express strong emotion or emphasis","category":"Punctuation","difficulty":1,"popularity":85,"definition":"The exclamation mark indicates excitement, surprise, anger, or any intense emotion in a sentence.","example":"Watch out! That was amazing!","contrast":"Period","images":[]}',
         1, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Semicolon',
         '{"description":"A punctuation mark linking two independent clauses","category":"Punctuation","difficulty":3,"popularity":70,"definition":"The semicolon connects two closely related independent clauses without using a conjunction.","example":"I love reading; it opens my mind.","contrast":"Comma","images":[]}',
         3, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Colon',
         '{"description":"A punctuation mark used to introduce a list, explanation, or quotation","category":"Punctuation","difficulty":2,"popularity":75,"definition":"The colon signals that what follows expands, explains, or lists what came before it.","example":"Bring the following: a pen, paper, and a book.","contrast":"Semicolon","images":[]}',
         2, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Apostrophe',
         '{"description":"A punctuation mark used for possession and contractions","category":"Punctuation","difficulty":2,"popularity":80,"definition":"The apostrophe indicates ownership or marks omitted letters in contractions.","example":"Sarah''s book, don''t, it''s","contrast":"Quotation Marks","images":[]}',
         2, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Quotation Marks',
         '{"description":"A pair of punctuation marks enclosing direct speech or a quotation","category":"Punctuation","difficulty":2,"popularity":80,"definition":"Quotation marks set off direct speech, quotations, titles of short works, or words used in a special sense.","example":"He said, ''Hello.''","contrast":"Apostrophe","images":[]}',
         2, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Parentheses',
         '{"description":"A pair of punctuation marks enclosing additional or explanatory information","category":"Punctuation","difficulty":2,"popularity":75,"definition":"Parentheses enclose supplementary material, clarifications, or asides that are not essential to the main sentence.","example":"He finally arrived (after two hours).","contrast":"Dash","images":[]}',
         2, ARRAY['concept', 'punctuation']),
        ('english_fundamentals', 'Dash',
         '{"description":"A punctuation mark indicating a strong break or interruption in thought","category":"Punctuation","difficulty":2,"popularity":70,"definition":"The dash creates a strong break in sentence flow, often for emphasis or to set off parenthetical content abruptly.","example":"I knew it — but I said nothing.","contrast":"Parentheses","images":[]}',
         2, ARRAY['concept', 'punctuation']),

        -- ── SENTENCE STRUCTURES (8) ──────────────────────────────────────
        ('english_fundamentals', 'Simple Sentence',
         '{"description":"A sentence with one independent clause and no dependent clauses","category":"Sentence Structure","difficulty":1,"popularity":85,"definition":"A simple sentence contains a single subject and predicate expressing a complete thought.","example":"The dog barked loudly.","contrast":"Compound Sentence","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Compound Sentence',
         '{"description":"A sentence with two or more independent clauses joined by a conjunction","category":"Sentence Structure","difficulty":2,"popularity":80,"definition":"A compound sentence connects two or more equally important independent clauses with a coordinating conjunction.","example":"I wanted to go, but it started raining.","contrast":"Simple Sentence","images":[]}',
         2, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Complex Sentence',
         '{"description":"A sentence with one independent clause and at least one dependent clause","category":"Sentence Structure","difficulty":3,"popularity":80,"definition":"A complex sentence combines a main clause with one or more subordinate clauses introduced by subordinating conjunctions.","example":"Although it rained, we still went hiking.","contrast":"Compound Sentence","images":[]}',
         3, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Compound-Complex Sentence',
         '{"description":"A sentence with multiple independent clauses and at least one dependent clause","category":"Sentence Structure","difficulty":4,"popularity":70,"definition":"A compound-complex sentence contains at least two independent clauses and one or more dependent clauses.","example":"Although I was tired, I finished my work, and then I went to bed.","contrast":"Complex Sentence","images":[]}',
         4, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Declarative Sentence',
         '{"description":"A sentence that makes a statement or expresses an opinion","category":"Sentence Structure","difficulty":1,"popularity":85,"definition":"A declarative sentence states a fact, opinion, or observation and ends with a period.","example":"The sun rises in the east.","contrast":"Interrogative Sentence","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Interrogative Sentence',
         '{"description":"A sentence that asks a question","category":"Sentence Structure","difficulty":1,"popularity":85,"definition":"An interrogative sentence seeks information and ends with a question mark.","example":"What time is the meeting?","contrast":"Declarative Sentence","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Imperative Sentence',
         '{"description":"A sentence that gives a command or makes a request","category":"Sentence Structure","difficulty":1,"popularity":80,"definition":"An imperative sentence issues a directive, request, or instruction, often with an implied subject.","example":"Please close the door.","contrast":"Exclamatory Sentence","images":[]}',
         1, ARRAY['concept', 'grammar']),
        ('english_fundamentals', 'Exclamatory Sentence',
         '{"description":"A sentence that expresses strong emotion or excitement","category":"Sentence Structure","difficulty":1,"popularity":80,"definition":"An exclamatory sentence conveys intense feeling and ends with an exclamation mark.","example":"What a beautiful sunset!","contrast":"Imperative Sentence","images":[]}',
         1, ARRAY['concept', 'grammar']),

        -- ── LITERARY DEVICES (16) ────────────────────────────────────────
        ('english_fundamentals', 'Metaphor',
         '{"description":"A direct comparison of two unlike things without using like or as","category":"Literary Device","difficulty":2,"popularity":90,"definition":"A metaphor asserts that one thing is another to create a vivid comparison or implied analogy.","example":"Time is a thief.","contrast":"Simile","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Simile',
         '{"description":"A comparison of two unlike things using like or as","category":"Literary Device","difficulty":2,"popularity":90,"definition":"A simile explicitly compares two different things using the words ''like'' or ''as'' to create imagery.","example":"As brave as a lion.","contrast":"Metaphor","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Alliteration',
         '{"description":"The repetition of initial consonant sounds in nearby words","category":"Literary Device","difficulty":2,"popularity":85,"definition":"Alliteration repeats the same sound at the beginning of adjacent or closely connected words for rhythmic effect.","example":"Peter Piper picked a peck of pickled peppers.","contrast":"Assonance","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Personification',
         '{"description":"Giving human qualities to non-human things or abstract ideas","category":"Literary Device","difficulty":2,"popularity":85,"definition":"Personification attributes human characteristics, emotions, or actions to inanimate objects or abstract concepts.","example":"The wind whispered through the trees.","contrast":"Metaphor","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Hyperbole',
         '{"description":"An extreme exaggeration used for emphasis or effect","category":"Literary Device","difficulty":2,"popularity":85,"definition":"Hyperbole deliberately exaggerates beyond reality to create strong feeling or humorous effect.","example":"I am so hungry I could eat a horse.","contrast":"Understatement","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Onomatopoeia',
         '{"description":"A word that phonetically imitates the sound it describes","category":"Literary Device","difficulty":2,"popularity":80,"definition":"Onomatopoeia uses words whose pronunciation mimics the natural sound of the thing they describe.","example":"buzz, crash, hiss, boom","contrast":"Alliteration","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Irony',
         '{"description":"The expression of meaning through language that signifies the opposite","category":"Literary Device","difficulty":3,"popularity":85,"definition":"Irony creates a contrast between what is said and what is actually meant or between expectation and reality.","example":"A fire station burning down.","contrast":"Sarcasm","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Foreshadowing',
         '{"description":"A hint or clue about events that will happen later in a story","category":"Literary Device","difficulty":3,"popularity":80,"definition":"Foreshadowing plants subtle hints or warnings about future plot developments.","example":"A character noticing a broken clock before a time-related tragedy.","contrast":"Flashback","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Flashback',
         '{"description":"An interruption that transports the narrative to an earlier time","category":"Literary Device","difficulty":3,"popularity":80,"definition":"A flashback breaks the chronological flow to show events that occurred before the current story timeline.","example":"A character remembering their childhood during a crisis.","contrast":"Foreshadowing","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Symbolism',
         '{"description":"The use of symbols to represent ideas or qualities beyond their literal meaning","category":"Literary Device","difficulty":3,"popularity":85,"definition":"Symbolism imbues objects, characters, or colors with deeper abstract meanings.","example":"A dove representing peace.","contrast":"Imagery","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Imagery',
         '{"description":"Vivid descriptive language that appeals to the senses","category":"Literary Device","difficulty":2,"popularity":85,"definition":"Imagery uses sensory details to create vivid mental pictures for the reader.","example":"The golden sand stretched endlessly under the blazing sun.","contrast":"Symbolism","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Oxymoron',
         '{"description":"A figure of speech combining contradictory terms","category":"Literary Device","difficulty":3,"popularity":75,"definition":"An oxymoron places two opposite or contradictory words together for rhetorical effect.","example":"deafening silence, jumbo shrimp","contrast":"Paradox","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Paradox',
         '{"description":"A seemingly contradictory statement that reveals a hidden truth","category":"Literary Device","difficulty":4,"popularity":75,"definition":"A paradox appears self-contradictory but upon reflection contains a deeper layer of meaning.","example":"I must be cruel to be kind.","contrast":"Oxymoron","images":[]}',
         4, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Allusion',
         '{"description":"An indirect reference to a person, event, or work of art","category":"Literary Device","difficulty":4,"popularity":70,"definition":"An allusion briefly and indirectly references a well-known figure, event, or cultural work.","example":"He had a Herculean task ahead.","contrast":"Metaphor","images":[]}',
         4, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Assonance',
         '{"description":"The repetition of vowel sounds in nearby words","category":"Literary Device","difficulty":3,"popularity":65,"definition":"Assonance repeats identical or similar vowel sounds in stressed syllables of adjacent words for internal rhyme.","example":"The rain in Spain falls mainly on the plain.","contrast":"Alliteration","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Consonance',
         '{"description":"The repetition of consonant sounds within or at the end of words","category":"Literary Device","difficulty":3,"popularity":60,"definition":"Consonance repeats consonant sounds in nearby words, often at the end of stressed syllables.","example":"pitter patter, last but not least","contrast":"Assonance","images":[]}',
         3, ARRAY['concept', 'literary-devices']),

        -- ── WORD FORMATION (8) ────────────────────────────────────────────
        ('english_fundamentals', 'Prefix',
         '{"description":"An affix placed before a root word to modify its meaning","category":"Word Formation","difficulty":2,"popularity":80,"definition":"A prefix is a group of letters added to the beginning of a base word to create a new meaning.","example":"un- in unhappy, re- in rewrite","contrast":"Suffix","images":[]}',
         2, ARRAY['concept', 'vocabulary']),
        ('english_fundamentals', 'Suffix',
         '{"description":"An affix placed after a root word to change its meaning or grammatical function","category":"Word Formation","difficulty":2,"popularity":80,"definition":"A suffix is added to the end of a word to alter its meaning or part of speech.","example":"-ly in quickly, -ness in kindness","contrast":"Prefix","images":[]}',
         2, ARRAY['concept', 'vocabulary']),
        ('english_fundamentals', 'Root Word',
         '{"description":"The core part of a word carrying its primary meaning","category":"Word Formation","difficulty":2,"popularity":75,"definition":"A root word is the basic lexical unit of a word, from which related words are formed by adding affixes.","example":"struct in construct, destroy, structure","contrast":"Prefix","images":[]}',
         2, ARRAY['concept', 'vocabulary']),
        ('english_fundamentals', 'Compound Word',
         '{"description":"A word formed by combining two or more independent words","category":"Word Formation","difficulty":2,"popularity":80,"definition":"A compound word joins two separate words to create a new word with its own meaning.","example":"notebook, toothpaste, bedroom","contrast":"Blend","images":[]}',
         2, ARRAY['concept', 'vocabulary']),
        ('english_fundamentals', 'Blend',
         '{"description":"A word formed by merging parts of two words","category":"Word Formation","difficulty":3,"popularity":70,"definition":"A blend (portmanteau) combines parts of two words to create a new term that retains aspects of both meanings.","example":"brunch (breakfast + lunch), smog (smoke + fog)","contrast":"Compound Word","images":[]}',
         3, ARRAY['concept', 'vocabulary']),
        ('english_fundamentals', 'Acronym',
         '{"description":"A word formed from the initial letters of a phrase","category":"Word Formation","difficulty":2,"popularity":85,"definition":"An acronym is pronounced as a word and formed from the first letters of a multi-word name.","example":"NASA, radar, AIDS","contrast":"Abbreviation","images":[]}',
         2, ARRAY['concept', 'vocabulary']),
        ('english_fundamentals', 'Abbreviation',
         '{"description":"A shortened form of a word or phrase","category":"Word Formation","difficulty":1,"popularity":80,"definition":"An abbreviation represents a longer word or phrase by omitting some letters, often ending with a period.","example":"Dr. for Doctor, etc. for et cetera","contrast":"Acronym","images":[]}',
         1, ARRAY['concept', 'vocabulary']),
        ('english_fundamentals', 'Contraction',
         '{"description":"A shortened word combining two words with omitted letters","category":"Word Formation","difficulty":1,"popularity":85,"definition":"A contraction combines two words by dropping letters and replacing them with an apostrophe.","example":"don''t, can''t, I''m, you''re","contrast":"Abbreviation","images":[]}',
         1, ARRAY['concept', 'vocabulary']),

        -- ── COMMON ERRORS (12) ────────────────────────────────────────────
        ('english_fundamentals', 'There/Their/They''re',
         '{"description":"A set of homophones commonly confused in writing","category":"Common Errors","difficulty":2,"popularity":90,"definition":"''There'' refers to a place, ''their'' shows possession, and ''they''re'' is a contraction of ''they are''.","example":"There is their house. They''re happy.","images":[]}',
         2, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Your/You''re',
         '{"description":"A pair of homophones frequently misused in writing","category":"Common Errors","difficulty":1,"popularity":90,"definition":"''Your'' indicates possession, while ''you''re'' is the contraction of ''you are''.","example":"You''re going to love your new car.","images":[]}',
         1, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Its/It''s',
         '{"description":"A pair of homophones that often cause confusion","category":"Common Errors","difficulty":2,"popularity":85,"definition":"''Its'' is the possessive form of ''it'', while ''it''s'' is the contraction of ''it is'' or ''it has''.","example":"It''s raining, so bring its leash.","images":[]}',
         2, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Affect/Effect',
         '{"description":"Verb and noun pair with distinct meanings often swapped","category":"Common Errors","difficulty":3,"popularity":80,"definition":"''Affect'' is usually a verb meaning to influence, while ''effect'' is usually a noun meaning a result.","example":"The weather affects mood. The drug had side effects.","images":[]}',
         3, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Then/Than',
         '{"description":"Two words confused in comparisons and sequences","category":"Common Errors","difficulty":2,"popularity":80,"definition":"''Then'' refers to time or sequence; ''than'' is used for comparisons.","example":"I ate first, then left. She is taller than me.","images":[]}',
         2, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Lose/Loose',
         '{"description":"A pair of words often mixed up due to similar spelling","category":"Common Errors","difficulty":2,"popularity":75,"definition":"''Lose'' means to misplace or fail to win (pronounced looz), while ''loose'' means not tight (pronounced loos).","example":"Did you lose your wallet? This knot is too loose.","images":[]}',
         2, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'To/Too/Two',
         '{"description":"Three homophones with completely different uses","category":"Common Errors","difficulty":1,"popularity":90,"definition":"''To'' is a preposition, ''too'' means also or excessively, and ''two'' is the number 2.","example":"I went to the store too. I bought two apples.","images":[]}',
         1, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Accept/Except',
         '{"description":"A verb and preposition pair frequently confused","category":"Common Errors","difficulty":2,"popularity":75,"definition":"''Accept'' means to receive willingly, while ''except'' means excluding or other than.","example":"I accept your offer. Everyone came except John.","images":[]}',
         2, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Principle/Principal',
         '{"description":"A pair of nouns with different meanings often swapped","category":"Common Errors","difficulty":3,"popularity":75,"definition":"''Principle'' is a fundamental truth or rule; ''principal'' means main or the head of a school.","example":"Honesty is a key principle. The school principal gave a speech.","images":[]}',
         3, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Stationary/Stationery',
         '{"description":"A pair of adjectives and nouns confused due to identical pronunciation","category":"Common Errors","difficulty":3,"popularity":65,"definition":"''Stationary'' means not moving, while ''stationery'' refers to writing materials like paper and pens.","example":"The car remained stationary. I bought new stationery for school.","images":[]}',
         3, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Complement/Compliment',
         '{"description":"A pair of words with distinct meanings often misspelled","category":"Common Errors","difficulty":3,"popularity":65,"definition":"''Complement'' means something that completes or enhances, while ''compliment'' is an expression of praise.","example":"The wine complements the meal. She received a nice compliment.","images":[]}',
         3, ARRAY['concept', 'usage']),
        ('english_fundamentals', 'Disinterested/Uninterested',
         '{"description":"A pair of adjectives with different meanings often confused","category":"Common Errors","difficulty":4,"popularity":60,"definition":"''Disinterested'' means impartial or unbiased, while ''uninterested'' means not interested or bored.","example":"A judge must be disinterested. She was uninterested in the lecture.","images":[]}',
         4, ARRAY['concept', 'usage']),

        -- ── FIGURATIVE LANGUAGE (10) ─────────────────────────────────────
        ('english_fundamentals', 'Idiom',
         '{"description":"A fixed expression whose meaning is not deducible from its individual words","category":"Figurative Language","difficulty":3,"popularity":85,"definition":"An idiom is a conventional phrase with a figurative meaning that differs from its literal interpretation.","example":"Spill the beans, kick the bucket","contrast":"Proverb","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Proverb',
         '{"description":"A short, traditional saying that imparts wisdom or advice","category":"Figurative Language","difficulty":3,"popularity":80,"definition":"A proverb is a folk saying that expresses a universal truth or piece of practical wisdom.","example":"A stitch in time saves nine.","contrast":"Idiom","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Cliché',
         '{"description":"An overused expression that has lost its original impact","category":"Figurative Language","difficulty":2,"popularity":70,"definition":"A cliché is a phrase or idea that has become trite through excessive use and lacks originality.","example":"Think outside the box, at the end of the day","contrast":"Idiom","images":[]}',
         2, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Pun',
         '{"description":"A humorous play on words exploiting multiple meanings or similar sounds","category":"Figurative Language","difficulty":3,"popularity":75,"definition":"A pun uses words with multiple meanings or similar sounds to create a humorous or witty effect.","example":"I used to be a baker, but I couldn''t make enough dough.","contrast":"Irony","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Euphemism',
         '{"description":"A mild or indirect expression substituted for a harsh or blunt one","category":"Figurative Language","difficulty":3,"popularity":75,"definition":"A euphemism replaces a direct, unpleasant, or offensive term with a softer, more polite alternative.","example":"Passed away instead of died","contrast":"Hyperbole","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Understatement',
         '{"description":"Deliberately making a situation seem less important than it is","category":"Figurative Language","difficulty":3,"popularity":65,"definition":"An understatement minimizes the significance of an event for rhetorical effect, often for irony.","example":"It''s just a scratch — said after a car crash.","contrast":"Hyperbole","images":[]}',
         3, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Malapropism',
         '{"description":"The mistaken use of a word in place of a similar-sounding one with a different meaning","category":"Figurative Language","difficulty":4,"popularity":60,"definition":"A malapropism substitutes an incorrect word for a similar-sounding correct word, creating humorous nonsense.","example":"He is the pineapple of politeness (instead of pinnacle).","contrast":"Pun","images":[]}',
         4, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Synecdoche',
         '{"description":"A figure of speech where a part represents the whole or vice versa","category":"Figurative Language","difficulty":4,"popularity":60,"definition":"Synecdoche uses a part of something to refer to the whole, or the whole to represent a part.","example":"All hands on deck (hands meaning sailors).","contrast":"Metonymy","images":[]}',
         4, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Metonymy',
         '{"description":"Replacing the name of something with something closely associated with it","category":"Figurative Language","difficulty":4,"popularity":60,"definition":"Metonymy substitutes a related term for the thing itself.","example":"The White House issued a statement (meaning the US government).","contrast":"Synecdoche","images":[]}',
         4, ARRAY['concept', 'literary-devices']),
        ('english_fundamentals', 'Litotes',
         '{"description":"An ironic understatement expressed through negation of the opposite","category":"Figurative Language","difficulty":4,"popularity":55,"definition":"Litotes affirms something by negating its contrary, creating understated emphasis.","example":"She is not unfriendly (meaning she is friendly).","contrast":"Understatement","images":[]}',
         4, ARRAY['concept', 'literary-devices']);

    END IF;
END $$;
