-- ===================================================================
-- Migration: seed 100 physics entities
-- Schema per PROCEDURAL_ENTITY_RULES.md — physical concepts use
-- Class B (Facts/Concepts), famous physicists use Class A (Persons).
-- ===================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM wordup_entities WHERE type = 'physics' LIMIT 1) THEN

        -- ═══════════════════════════════════════════════════════════
        -- MECHANICS (20)
        -- ═══════════════════════════════════════════════════════════
        INSERT INTO wordup_entities (type, label, metadata, difficulty, tags) VALUES
        ('physics', 'Force',
         '{"description":"A push or pull that changes an object''s motion","category":"Mechanics","difficulty":1,"popularity":95,"group":"Classical Mechanics","primary_val":"F","secondary_val":"Newtons (N)","definition":"A force is any interaction that, when unopposed, changes the motion of an object.","formula":"F = ma","symbol":"F","unit":"N","images":[]}',
         1, ARRAY['concept', 'mechanics']),
        ('physics', 'Mass',
         '{"description":"The amount of matter in an object","category":"Mechanics","difficulty":1,"popularity":95,"group":"Classical Mechanics","primary_val":"m","secondary_val":"Kilograms (kg)","definition":"Mass is a fundamental measure of the amount of matter, determining an object''s resistance to acceleration.","symbol":"m","unit":"kg","images":[]}',
         1, ARRAY['concept', 'mechanics']),
        ('physics', 'Velocity',
         '{"description":"Speed in a given direction","category":"Mechanics","difficulty":1,"popularity":90,"group":"Kinematics","primary_val":"v","secondary_val":"m/s","definition":"Velocity is the rate of change of displacement, combining speed with a specific direction vector.","formula":"v = d/t","symbol":"v","unit":"m/s","images":[]}',
         1, ARRAY['concept', 'mechanics']),
        ('physics', 'Acceleration',
         '{"description":"The rate of change of velocity over time","category":"Mechanics","difficulty":1,"popularity":90,"group":"Kinematics","primary_val":"a","secondary_val":"m/s^2","definition":"Acceleration is how quickly an object changes its velocity, including changes in speed or direction.","formula":"a = F/m","symbol":"a","unit":"m/s^2","images":[]}',
         1, ARRAY['concept', 'mechanics']),
        ('physics', 'Momentum',
         '{"description":"The product of an object''s mass and velocity","category":"Mechanics","difficulty":2,"popularity":85,"group":"Classical Mechanics","primary_val":"p","secondary_val":"kg*m/s","definition":"Momentum quantifies the motion of an object and is conserved in isolated systems during collisions.","formula":"p = mv","symbol":"p","unit":"kg*m/s","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Inertia',
         '{"description":"An object''s resistance to changes in its state of motion","category":"Mechanics","difficulty":2,"popularity":80,"group":"Classical Mechanics","primary_val":"I","secondary_val":"—","definition":"Inertia is the tendency of an object to remain at rest or in uniform motion unless acted upon by an external force.","symbol":"I","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Friction',
         '{"description":"A resistive force opposing relative motion between surfaces","category":"Mechanics","difficulty":2,"popularity":85,"group":"Classical Mechanics","primary_val":"F_f","secondary_val":"Newtons (N)","definition":"Friction is a contact force that opposes sliding or rolling motion between two surfaces in contact.","formula":"F_f = μN","symbol":"F_f","unit":"N","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Gravity',
         '{"description":"The attractive force between objects with mass","category":"Mechanics","difficulty":2,"popularity":95,"group":"Classical Mechanics","primary_val":"F_g","secondary_val":"m/s^2","definition":"Gravity is a universal force that attracts any two objects with mass proportional to their masses and inversely proportional to distance squared.","formula":"F = G(m1*m2)/r^2","symbol":"g","unit":"m/s^2","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Work',
         '{"description":"Energy transferred when a force moves an object over a distance","category":"Mechanics","difficulty":2,"popularity":85,"group":"Classical Mechanics","primary_val":"W","secondary_val":"Joules (J)","definition":"Work is done when a force acts on an object and causes it to displace in the direction of the force.","formula":"W = F*d","symbol":"W","unit":"J","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Kinetic Energy',
         '{"description":"Energy of an object due to its motion","category":"Mechanics","difficulty":2,"popularity":90,"group":"Classical Mechanics","primary_val":"KE","secondary_val":"Joules (J)","definition":"Kinetic energy is the energy an object possesses because of its motion, proportional to mass and the square of velocity.","formula":"KE = 0.5*m*v^2","symbol":"KE","unit":"J","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Potential Energy',
         '{"description":"Stored energy due to an object''s position or configuration","category":"Mechanics","difficulty":2,"popularity":90,"group":"Classical Mechanics","primary_val":"PE","secondary_val":"Joules (J)","definition":"Potential energy is energy stored in an object due to its position in a force field, such as gravitational height.","formula":"PE = mgh","symbol":"PE","unit":"J","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Power',
         '{"description":"The rate at which work is done or energy is transferred","category":"Mechanics","difficulty":2,"popularity":85,"group":"Classical Mechanics","primary_val":"P","secondary_val":"Watts (W)","definition":"Power measures how quickly work is performed or energy is converted from one form to another.","formula":"P = W/t","symbol":"P","unit":"W","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Newton''s First Law',
         '{"description":"An object at rest stays at rest unless acted upon by a net external force","category":"Mechanics","difficulty":2,"popularity":95,"group":"Classical Mechanics","primary_val":"Law of Inertia","secondary_val":"—","definition":"Newton''s first law states that an object maintains its state of rest or uniform motion unless compelled to change by an external force.","famous_for":"Law of Inertia","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Newton''s Second Law',
         '{"description":"Force equals mass times acceleration","category":"Mechanics","difficulty":2,"popularity":95,"group":"Classical Mechanics","primary_val":"F = ma","secondary_val":"—","definition":"Newton''s second law states that the acceleration of an object is directly proportional to the net force and inversely proportional to its mass.","formula":"F = ma","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Newton''s Third Law',
         '{"description":"For every action there is an equal and opposite reaction","category":"Mechanics","difficulty":2,"popularity":95,"group":"Classical Mechanics","primary_val":"Action-Reaction","secondary_val":"—","definition":"Newton''s third law states that forces always occur in equal and opposite pairs between interacting objects.","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Torque',
         '{"description":"A twisting force that causes rotation","category":"Mechanics","difficulty":3,"popularity":80,"group":"Rotational Mechanics","primary_val":"τ","secondary_val":"N*m","definition":"Torque is the rotational equivalent of linear force, depending on the force magnitude and the lever arm distance.","formula":"τ = rFsinθ","symbol":"τ","unit":"N*m","images":[]}',
         3, ARRAY['concept', 'mechanics']),
        ('physics', 'Centripetal Force',
         '{"description":"A force that keeps an object moving in a circular path","category":"Mechanics","difficulty":3,"popularity":80,"group":"Rotational Mechanics","primary_val":"F_c","secondary_val":"Newtons (N)","definition":"Centripetal force acts toward the center of a circular path, continuously changing the direction of an object''s velocity.","formula":"F_c = mv^2/r","symbol":"F_c","unit":"N","images":[]}',
         3, ARRAY['concept', 'mechanics']),
        ('physics', 'Simple Harmonic Motion',
         '{"description":"A periodic oscillation where restoring force is proportional to displacement","category":"Mechanics","difficulty":3,"popularity":75,"group":"Oscillations","primary_val":"SHM","secondary_val":"—","definition":"Simple harmonic motion is a type of periodic motion where the restoring force is directly proportional to the displacement from equilibrium.","example":"A mass on a spring or a pendulum at small angles","images":[]}',
         3, ARRAY['concept', 'mechanics']),
        ('physics', 'Elasticity',
         '{"description":"The ability of a material to return to its original shape after deformation","category":"Mechanics","difficulty":2,"popularity":75,"group":"Materials","primary_val":"E","secondary_val":"Pascals (Pa)","definition":"Elasticity is the property of a material that allows it to regain its original shape after the deforming force is removed.","symbol":"E","unit":"Pa","images":[]}',
         2, ARRAY['concept', 'mechanics']),
        ('physics', 'Pressure',
         '{"description":"Force applied perpendicularly per unit area","category":"Mechanics","difficulty":1,"popularity":85,"group":"Fluid Mechanics","primary_val":"P","secondary_val":"Pascals (Pa)","definition":"Pressure is the amount of force acting perpendicularly on a unit area of a surface.","formula":"P = F/A","symbol":"P","unit":"Pa","images":[]}',
         1, ARRAY['concept', 'mechanics']),

        -- ═══════════════════════════════════════════════════════════
        -- THERMODYNAMICS (10)
        -- ═══════════════════════════════════════════════════════════
        ('physics', 'Temperature',
         '{"description":"A measure of the average kinetic energy of particles in a substance","category":"Thermodynamics","difficulty":1,"popularity":95,"group":"Thermodynamics","primary_val":"T","secondary_val":"Kelvin (K)","definition":"Temperature quantifies how hot or cold an object is relative to a standard scale, reflecting particle motion.","symbol":"T","unit":"K","images":[]}',
         1, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Heat',
         '{"description":"Energy transferred between systems due to a temperature difference","category":"Thermodynamics","difficulty":2,"popularity":90,"group":"Thermodynamics","primary_val":"Q","secondary_val":"Joules (J)","definition":"Heat is the flow of thermal energy from a hotter object to a cooler object through conduction, convection, or radiation.","symbol":"Q","unit":"J","images":[]}',
         2, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Internal Energy',
         '{"description":"The total energy stored within a system from molecular motion and interactions","category":"Thermodynamics","difficulty":3,"popularity":75,"group":"Thermodynamics","primary_val":"U","secondary_val":"Joules (J)","definition":"Internal energy is the sum of kinetic and potential energies of all particles within a thermodynamic system.","symbol":"U","unit":"J","images":[]}',
         3, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Entropy',
         '{"description":"A measure of disorder or randomness in a system","category":"Thermodynamics","difficulty":3,"popularity":85,"group":"Thermodynamics","primary_val":"S","secondary_val":"J/K","definition":"Entropy quantifies the number of possible microscopic configurations of a system, always increasing in isolated systems.","symbol":"S","unit":"J/K","images":[]}',
         3, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Specific Heat Capacity',
         '{"description":"The heat required to raise the temperature of one kilogram of a substance by one kelvin","category":"Thermodynamics","difficulty":2,"popularity":75,"group":"Thermodynamics","primary_val":"c","secondary_val":"J/(kg*K)","definition":"Specific heat capacity is the amount of heat per unit mass needed to increase the temperature of a substance by one degree.","formula":"Q = mcΔT","symbol":"c","unit":"J/(kg*K)","images":[]}',
         2, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Thermal Conduction',
         '{"description":"Heat transfer through direct particle collisions within a material","category":"Thermodynamics","difficulty":2,"popularity":75,"group":"Heat Transfer","primary_val":"k","secondary_val":"W/(m*K)","definition":"Thermal conduction is the transfer of heat energy through a substance via particle collisions without bulk movement.","symbol":"k","unit":"W/(m*K)","images":[]}',
         2, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Convection',
         '{"description":"Heat transfer through the bulk movement of fluids","category":"Thermodynamics","difficulty":2,"popularity":75,"group":"Heat Transfer","primary_val":"—","secondary_val":"—","definition":"Convection transfers heat by the macroscopic movement of fluid particles from hotter to cooler regions.","example":"Boiling water or atmospheric circulation","contrast":"Thermal Conduction","images":[]}',
         2, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Thermal Radiation',
         '{"description":"Heat transfer via electromagnetic waves without a medium","category":"Thermodynamics","difficulty":2,"popularity":75,"group":"Heat Transfer","primary_val":"—","secondary_val":"—","definition":"Thermal radiation emits energy as electromagnetic waves from all objects above absolute zero, requiring no medium.","example":"Heat from the Sun reaching Earth","contrast":"Convection","images":[]}',
         2, ARRAY['concept', 'thermodynamics']),
        ('physics', 'First Law of Thermodynamics',
         '{"description":"Energy cannot be created or destroyed, only converted between forms","category":"Thermodynamics","difficulty":3,"popularity":90,"group":"Thermodynamics","primary_val":"ΔU = Q - W","secondary_val":"—","definition":"The first law states that the change in a system''s internal energy equals heat added minus work done by the system.","formula":"ΔU = Q - W","images":[]}',
         3, ARRAY['concept', 'thermodynamics']),
        ('physics', 'Second Law of Thermodynamics',
         '{"description":"The total entropy of an isolated system always increases over time","category":"Thermodynamics","difficulty":3,"popularity":90,"group":"Thermodynamics","primary_val":"ΔS ≥ 0","secondary_val":"—","definition":"The second law states that natural processes increase the universe''s entropy, making some energy conversions irreversible.","contrast":"First Law of Thermodynamics","images":[]}',
         3, ARRAY['concept', 'thermodynamics']),

        -- ═══════════════════════════════════════════════════════════
        -- WAVES & SOUND (10)
        -- ═══════════════════════════════════════════════════════════
        ('physics', 'Wave',
         '{"description":"A disturbance that transfers energy through a medium without transferring matter","category":"Waves & Sound","difficulty":1,"popularity":85,"group":"Wave Mechanics","primary_val":"—","secondary_val":"—","definition":"A wave is an oscillation that travels through space and matter, carrying energy from one point to another.","example":"Water waves, sound waves, light waves","images":[]}',
         1, ARRAY['concept', 'waves']),
        ('physics', 'Frequency',
         '{"description":"The number of wave cycles passing a point per second","category":"Waves & Sound","difficulty":1,"popularity":90,"group":"Wave Mechanics","primary_val":"f","secondary_val":"Hertz (Hz)","definition":"Frequency is the rate at which a wave oscillates, measured in cycles per second.","formula":"f = 1/T","symbol":"f","unit":"Hz","images":[]}',
         1, ARRAY['concept', 'waves']),
        ('physics', 'Wavelength',
         '{"description":"The distance between consecutive corresponding points of a wave","category":"Waves & Sound","difficulty":1,"popularity":90,"group":"Wave Mechanics","primary_val":"λ","secondary_val":"Meters (m)","definition":"Wavelength is the spatial period of a wave, the distance over which the wave shape repeats.","formula":"λ = v/f","symbol":"λ","unit":"m","images":[]}',
         1, ARRAY['concept', 'waves']),
        ('physics', 'Amplitude',
         '{"description":"The maximum displacement of a wave from its equilibrium position","category":"Waves & Sound","difficulty":1,"popularity":85,"group":"Wave Mechanics","primary_val":"A","secondary_val":"Meters (m)","definition":"Amplitude measures the height or intensity of a wave, determining its energy and loudness for sound.","symbol":"A","unit":"m","images":[]}',
         1, ARRAY['concept', 'waves']),
        ('physics', 'Resonance',
         '{"description":"When a system oscillates at maximum amplitude at its natural frequency","category":"Waves & Sound","difficulty":3,"popularity":80,"group":"Wave Mechanics","primary_val":"—","secondary_val":"—","definition":"Resonance occurs when an external driving force matches a system''s natural frequency, producing large amplitude oscillations.","example":"An opera singer shattering a glass","images":[]}',
         3, ARRAY['concept', 'waves']),
        ('physics', 'Doppler Effect',
         '{"description":"The change in wave frequency due to relative motion between source and observer","category":"Waves & Sound","difficulty":3,"popularity":85,"group":"Wave Mechanics","primary_val":"—","secondary_val":"—","definition":"The Doppler effect shifts the observed frequency of a wave when the source moves toward or away from the observer.","example":"A siren sounding higher as it approaches and lower as it recedes","images":[]}',
         3, ARRAY['concept', 'waves']),
        ('physics', 'Wave Interference',
         '{"description":"The superposition of two or more waves producing a resultant wave","category":"Waves & Sound","difficulty":3,"popularity":80,"group":"Wave Mechanics","primary_val":"—","secondary_val":"—","definition":"Interference occurs when waves overlap, combining constructively (in phase) or destructively (out of phase).","contrast":"Diffraction","images":[]}',
         3, ARRAY['concept', 'waves']),
        ('physics', 'Diffraction',
         '{"description":"The bending of waves around obstacles or through openings","category":"Waves & Sound","difficulty":3,"popularity":75,"group":"Wave Mechanics","primary_val":"—","secondary_val":"—","definition":"Diffraction is the spreading of waves when they pass through an aperture or around an obstacle.","example":"Sound bending around a corner","contrast":"Wave Interference","images":[]}',
         3, ARRAY['concept', 'waves']),
        ('physics', 'Polarization',
         '{"description":"The restriction of wave vibrations to a specific direction","category":"Waves & Sound","difficulty":3,"popularity":70,"group":"Wave Mechanics","primary_val":"—","secondary_val":"—","definition":"Polarization aligns the oscillations of a transverse wave to a single plane, typically for light waves.","example":"Polarized sunglasses reducing glare","images":[]}',
         3, ARRAY['concept', 'waves']),
        ('physics', 'Speed of Sound',
         '{"description":"The distance sound travels per unit time through a medium","category":"Waves & Sound","difficulty":2,"popularity":85,"group":"Acoustics","primary_val":"v_sound","secondary_val":"343 m/s (air)","definition":"The speed of sound depends on the medium''s density and elasticity, traveling fastest in solids and slowest in gases.","value":"343","unit":"m/s","images":[]}',
         2, ARRAY['concept', 'waves']),

        -- ═══════════════════════════════════════════════════════════
        -- OPTICS (10)
        -- ═══════════════════════════════════════════════════════════
        ('physics', 'Light',
         '{"description":"Electromagnetic radiation visible to the human eye","category":"Optics","difficulty":1,"popularity":95,"group":"Optics","primary_val":"c","secondary_val":"3×10^8 m/s","definition":"Light is electromagnetic radiation that exhibits both wave and particle properties, traveling at the fastest speed in the universe.","symbol":"c","value":"299792458","unit":"m/s","images":[]}',
         1, ARRAY['concept', 'optics']),
        ('physics', 'Reflection',
         '{"description":"The bouncing of light off a surface","category":"Optics","difficulty":1,"popularity":90,"group":"Optics","primary_val":"—","secondary_val":"—","definition":"Reflection occurs when light rays bounce back from a surface, following the law of equal incidence and reflection angles.","formula":"θ_i = θ_r","contrast":"Refraction","images":[]}',
         1, ARRAY['concept', 'optics']),
        ('physics', 'Refraction',
         '{"description":"The bending of light when passing between different media","category":"Optics","difficulty":2,"popularity":90,"group":"Optics","primary_val":"n","secondary_val":"—","definition":"Refraction is the change in direction of light as it passes from one transparent medium into another due to speed change.","contrast":"Reflection","images":[]}',
         2, ARRAY['concept', 'optics']),
        ('physics', 'Lens',
         '{"description":"A transparent optical device that focuses or disperses light","category":"Optics","difficulty":2,"popularity":85,"group":"Optics","primary_val":"f","secondary_val":"Meters (m)","definition":"A lens refracts light to converge or diverge beams, used in cameras, glasses, and microscopes.","symbol":"f (focal length)","unit":"m","images":[]}',
         2, ARRAY['concept', 'optics']),
        ('physics', 'Mirror',
         '{"description":"A reflective surface that forms images by reflection","category":"Optics","difficulty":1,"popularity":85,"group":"Optics","primary_val":"—","secondary_val":"—","definition":"A mirror is a smooth surface that reflects light to form an image, used in telescopes, vehicles, and everyday life.","example":"Plane mirrors, concave mirrors, convex mirrors","images":[]}',
         1, ARRAY['concept', 'optics']),
        ('physics', 'Snell''s Law',
         '{"description":"The relationship between angles of incidence and refraction","category":"Optics","difficulty":3,"popularity":80,"group":"Optics","primary_val":"n1 sin θ1 = n2 sin θ2","secondary_val":"—","definition":"Snell''s law describes how light bends when crossing the boundary between two media with different refractive indices.","formula":"n1 sin θ1 = n2 sin θ2","images":[]}',
         3, ARRAY['concept', 'optics']),
        ('physics', 'Focal Length',
         '{"description":"The distance from a lens or mirror to its focal point","category":"Optics","difficulty":2,"popularity":80,"group":"Optics","primary_val":"f","secondary_val":"Meters (m)","definition":"Focal length is the measure of how strongly a lens or mirror converges or diverges light.","symbol":"f","unit":"m","images":[]}',
         2, ARRAY['concept', 'optics']),
        ('physics', 'Dispersion',
         '{"description":"The separation of light into its constituent wavelengths","category":"Optics","difficulty":2,"popularity":80,"group":"Optics","primary_val":"—","secondary_val":"—","definition":"Dispersion occurs when different frequencies of light bend by different amounts, separating white light into a spectrum.","example":"A rainbow created by a prism","images":[]}',
         2, ARRAY['concept', 'optics']),
        ('physics', 'Electromagnetic Spectrum',
         '{"description":"The entire range of electromagnetic radiation frequencies","category":"Optics","difficulty":2,"popularity":85,"group":"Optics","primary_val":"—","secondary_val":"—","definition":"The electromagnetic spectrum spans from radio waves (longest) to gamma rays (shortest), including visible light in between.","example":"Radio, microwave, infrared, visible, UV, X-ray, gamma ray","images":[]}',
         2, ARRAY['concept', 'optics']),
        ('physics', 'Total Internal Reflection',
         '{"description":"Complete reflection of light within a denser medium","category":"Optics","difficulty":3,"popularity":75,"group":"Optics","primary_val":"θ_c","secondary_val":"Degrees","definition":"Total internal reflection occurs when light traveling from a denser to rarer medium exceeds the critical angle.","example":"Fiber optics transmitting light through cables","images":[]}',
         3, ARRAY['concept', 'optics']),

        -- ═══════════════════════════════════════════════════════════
        -- ELECTRICITY & MAGNETISM (16)
        -- ═══════════════════════════════════════════════════════════
        ('physics', 'Electric Charge',
         '{"description":"A fundamental property of matter that causes electromagnetic interactions","category":"Electricity & Magnetism","difficulty":1,"popularity":90,"group":"Electromagnetism","primary_val":"Q","secondary_val":"Coulombs (C)","definition":"Electric charge is the physical property of matter that causes it to experience a force in an electromagnetic field.","symbol":"Q","unit":"C","images":[]}',
         1, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Electric Current',
         '{"description":"The flow of electric charge through a conductor","category":"Electricity & Magnetism","difficulty":1,"popularity":90,"group":"Electromagnetism","primary_val":"I","secondary_val":"Amperes (A)","definition":"Electric current is the rate of flow of electric charge past a point in a circuit.","formula":"I = Q/t","symbol":"I","unit":"A","images":[]}',
         1, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Voltage',
         '{"description":"The electric potential difference between two points","category":"Electricity & Magnetism","difficulty":1,"popularity":90,"group":"Electromagnetism","primary_val":"V","secondary_val":"Volts (V)","definition":"Voltage is the electrical potential difference that drives current through a circuit.","formula":"V = IR","symbol":"V","unit":"V","images":[]}',
         1, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Electrical Resistance',
         '{"description":"The opposition to the flow of electric current","category":"Electricity & Magnetism","difficulty":2,"popularity":85,"group":"Electromagnetism","primary_val":"R","secondary_val":"Ohms (Ω)","definition":"Resistance measures how strongly a material opposes the flow of electric current.","formula":"R = V/I","symbol":"R","unit":"Ω","images":[]}',
         2, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Capacitance',
         '{"description":"The ability of a system to store electric charge","category":"Electricity & Magnetism","difficulty":3,"popularity":75,"group":"Electromagnetism","primary_val":"C","secondary_val":"Farads (F)","definition":"Capacitance is the ratio of the change in electric charge to the corresponding change in electric potential.","formula":"C = Q/V","symbol":"C","unit":"F","images":[]}',
         3, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Magnetic Field',
         '{"description":"A region where magnetic forces act on moving charges","category":"Electricity & Magnetism","difficulty":2,"popularity":85,"group":"Electromagnetism","primary_val":"B","secondary_val":"Teslas (T)","definition":"A magnetic field is a vector field that exerts a force on moving electric charges and magnetic dipoles.","symbol":"B","unit":"T","images":[]}',
         2, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Electromagnetism',
         '{"description":"The unification of electric and magnetic forces","category":"Electricity & Magnetism","difficulty":2,"popularity":90,"group":"Electromagnetism","primary_val":"—","secondary_val":"—","definition":"Electromagnetism is the fundamental interaction between electrically charged particles, governing electricity and magnetism.","famous_for":"Maxwell''s equations unify electricity, magnetism, and light","images":[]}',
         2, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Ohm''s Law',
         '{"description":"The relationship between voltage, current, and resistance","category":"Electricity & Magnetism","difficulty":1,"popularity":95,"group":"Electromagnetism","primary_val":"V = IR","secondary_val":"—","definition":"Ohm''s law states that current through a conductor is directly proportional to voltage and inversely proportional to resistance.","formula":"V = IR","images":[]}',
         1, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Coulomb''s Law',
         '{"description":"The force between two charged particles","category":"Electricity & Magnetism","difficulty":3,"popularity":85,"group":"Electromagnetism","primary_val":"F = k(q1*q2)/r^2","secondary_val":"—","definition":"Coulomb''s law states that the electric force between charges is proportional to the product of charges and inversely proportional to distance squared.","formula":"F = k(q1*q2)/r^2","images":[]}',
         3, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Faraday''s Law of Induction',
         '{"description":"A changing magnetic field induces an electromotive force","category":"Electricity & Magnetism","difficulty":3,"popularity":85,"group":"Electromagnetism","primary_val":"ε = -dΦ/dt","secondary_val":"—","definition":"Faraday''s law states that the induced voltage in a circuit is proportional to the rate of change of magnetic flux.","formula":"ε = -dΦ/dt","images":[]}',
         3, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Electric Circuit',
         '{"description":"A closed path through which electric current flows","category":"Electricity & Magnetism","difficulty":1,"popularity":85,"group":"Electromagnetism","primary_val":"—","secondary_val":"—","definition":"An electric circuit is a closed loop of conducting material that allows current to flow from a source through components and back.","example":"A simple battery and light bulb circuit","images":[]}',
         1, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Conductor',
         '{"description":"A material that allows electric current to flow easily","category":"Electricity & Magnetism","difficulty":1,"popularity":85,"group":"Electromagnetism","primary_val":"—","secondary_val":"—","definition":"A conductor has free electrons that readily carry electric current with low resistance.","example":"Copper, aluminum, silver","contrast":"Insulator","images":[]}',
         1, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Insulator',
         '{"description":"A material that resists the flow of electric current","category":"Electricity & Magnetism","difficulty":1,"popularity":85,"group":"Electromagnetism","primary_val":"—","secondary_val":"—","definition":"An insulator has tightly bound electrons that do not move easily, preventing current flow.","example":"Rubber, plastic, glass","contrast":"Conductor","images":[]}',
         1, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Semiconductor',
         '{"description":"A material with conductivity between conductors and insulators","category":"Electricity & Magnetism","difficulty":3,"popularity":85,"group":"Electromagnetism","primary_val":"—","secondary_val":"—","definition":"Semiconductors have variable conductivity that can be controlled by doping or applied voltage, enabling modern electronics.","example":"Silicon, germanium","images":[]}',
         3, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Transformer',
         '{"description":"A device that transfers electrical energy between circuits via electromagnetic induction","category":"Electricity & Magnetism","difficulty":3,"popularity":75,"group":"Electromagnetism","primary_val":"V_p/V_s = N_p/N_s","secondary_val":"—","definition":"A transformer uses electromagnetic induction to change voltage levels while conserving power between primary and secondary coils.","formula":"V_p/V_s = N_p/N_s","images":[]}',
         3, ARRAY['concept', 'electromagnetism']),
        ('physics', 'Inductance',
         '{"description":"The property of a conductor to oppose changes in current","category":"Electricity & Magnetism","difficulty":3,"popularity":70,"group":"Electromagnetism","primary_val":"L","secondary_val":"Henries (H)","definition":"Inductance is the tendency of an electrical conductor to oppose changes in current flowing through it, storing energy in a magnetic field.","formula":"V = L(dI/dt)","symbol":"L","unit":"H","images":[]}',
         3, ARRAY['concept', 'electromagnetism']),

        -- ═══════════════════════════════════════════════════════════
        -- MODERN PHYSICS (12)
        -- ═══════════════════════════════════════════════════════════
        ('physics', 'Quantum Mechanics',
         '{"description":"The branch of physics describing nature at atomic and subatomic scales","category":"Modern Physics","difficulty":4,"popularity":95,"group":"Quantum Physics","primary_val":"—","secondary_val":"—","definition":"Quantum mechanics is the fundamental theory that describes the behavior of matter and energy at the smallest scales.","famous_for":"Wave-particle duality and quantization of energy","images":[]}',
         4, ARRAY['concept', 'modern-physics']),
        ('physics', 'Photon',
         '{"description":"A fundamental particle of light carrying electromagnetic energy","category":"Modern Physics","difficulty":2,"popularity":90,"group":"Quantum Physics","primary_val":"γ","secondary_val":"—","definition":"A photon is a quantum of electromagnetic radiation with zero mass, traveling at the speed of light.","symbol":"γ","images":[]}',
         2, ARRAY['concept', 'modern-physics']),
        ('physics', 'Electron',
         '{"description":"A negatively charged subatomic particle orbiting the atomic nucleus","category":"Modern Physics","difficulty":1,"popularity":90,"group":"Particle Physics","primary_val":"e","secondary_val":"−1.602×10^(−19) C","definition":"An electron is a stable subatomic particle with a negative elementary charge, responsible for electricity and chemical bonding.","symbol":"e","images":[]}',
         1, ARRAY['concept', 'modern-physics']),
        ('physics', 'Neutron',
         '{"description":"A neutral subatomic particle found in atomic nuclei","category":"Modern Physics","difficulty":1,"popularity":85,"group":"Particle Physics","primary_val":"n","secondary_val":"—","definition":"A neutron is a subatomic particle with no electric charge, found in the nucleus of atoms alongside protons.","symbol":"n","contrast":"Proton","images":[]}',
         1, ARRAY['concept', 'modern-physics']),
        ('physics', 'Proton',
         '{"description":"A positively charged subatomic particle in the atomic nucleus","category":"Modern Physics","difficulty":1,"popularity":85,"group":"Particle Physics","primary_val":"p","secondary_val":"+1.602×10^(−19) C","definition":"A proton is a stable subatomic particle with a positive elementary charge, determining the element''s atomic number.","symbol":"p","contrast":"Neutron","images":[]}',
         1, ARRAY['concept', 'modern-physics']),
        ('physics', 'Radioactive Decay',
         '{"description":"The spontaneous breakdown of an unstable atomic nucleus","category":"Modern Physics","difficulty":3,"popularity":85,"group":"Nuclear Physics","primary_val":"—","secondary_val":"—","definition":"Radioactive decay is the process by which an unstable atomic nucleus loses energy by emitting radiation.","example":"Alpha, beta, and gamma decay","images":[]}',
         3, ARRAY['concept', 'modern-physics']),
        ('physics', 'Nuclear Fission',
         '{"description":"The splitting of a heavy atomic nucleus into smaller fragments","category":"Modern Physics","difficulty":3,"popularity":85,"group":"Nuclear Physics","primary_val":"—","secondary_val":"—","definition":"Nuclear fission splits a heavy nucleus into lighter nuclei, releasing large amounts of energy and neutrons.","example":"Uranium-235 fission in nuclear reactors","contrast":"Nuclear Fusion","images":[]}',
         3, ARRAY['concept', 'modern-physics']),
        ('physics', 'Nuclear Fusion',
         '{"description":"The combining of light atomic nuclei into a heavier nucleus","category":"Modern Physics","difficulty":3,"popularity":85,"group":"Nuclear Physics","primary_val":"—","secondary_val":"—","definition":"Nuclear fusion fuses two light nuclei into a heavier nucleus, releasing enormous energy — the power source of stars.","example":"Hydrogen fusion in the Sun","contrast":"Nuclear Fission","images":[]}',
         3, ARRAY['concept', 'modern-physics']),
        ('physics', 'Theory of Relativity',
         '{"description":"Einstein''s theory describing space, time, and gravity","category":"Modern Physics","difficulty":4,"popularity":95,"group":"Relativity","primary_val":"E = mc^2","secondary_val":"—","definition":"Relativity revolutionized physics by showing that space and time are relative and that gravity curves spacetime.","formula":"E = mc^2","famous_for":"E = mc^2 and time dilation","images":[]}',
         4, ARRAY['concept', 'modern-physics']),
        ('physics', 'Wave-Particle Duality',
         '{"description":"The principle that quantum entities exhibit both wave and particle properties","category":"Modern Physics","difficulty":4,"popularity":90,"group":"Quantum Physics","primary_val":"—","secondary_val":"—","definition":"Wave-particle duality states that every quantum entity can behave as both a wave and a particle depending on measurement.","famous_for":"Double-slit experiment showing dual nature of light","images":[]}',
         4, ARRAY['concept', 'modern-physics']),
        ('physics', 'Uncertainty Principle',
         '{"description":"The impossibility of simultaneously knowing precise position and momentum","category":"Modern Physics","difficulty":4,"popularity":90,"group":"Quantum Physics","primary_val":"ΔxΔp ≥ h/4π","secondary_val":"—","definition":"Heisenberg''s uncertainty principle states that the more precisely position is known, the less precisely momentum can be known.","formula":"ΔxΔp ≥ h/4π","famous_for":"Heisenberg''s uncertainty principle","images":[]}',
         4, ARRAY['concept', 'modern-physics']),
        ('physics', 'Quantum Entanglement',
         '{"description":"A quantum phenomenon where particles remain correlated across distances","category":"Modern Physics","difficulty":5,"popularity":85,"group":"Quantum Physics","primary_val":"—","secondary_val":"—","definition":"Quantum entanglement links particles so that measuring one instantly influences its partner, regardless of distance.","famous_for":"Spooky action at a distance","images":[]}',
         5, ARRAY['concept', 'modern-physics']),

        -- ═══════════════════════════════════════════════════════════
        -- CONSTANTS & UNITS (10)
        -- ═══════════════════════════════════════════════════════════
        ('physics', 'Speed of Light',
         '{"description":"The universal speed limit at which all massless particles travel","category":"Constants & Units","difficulty":2,"popularity":95,"group":"Physical Constants","primary_val":"c","secondary_val":"299,792,458 m/s","definition":"The speed of light in vacuum is a fundamental constant of nature, approximately 300 million meters per second.","symbol":"c","value":"299792458","unit":"m/s","images":[]}',
         2, ARRAY['concept', 'constants']),
        ('physics', 'Planck''s Constant',
         '{"description":"The fundamental quantum of action in quantum mechanics","category":"Constants & Units","difficulty":3,"popularity":90,"group":"Physical Constants","primary_val":"h","secondary_val":"6.626×10^(−34) J*s","definition":"Planck''s constant relates the energy of a photon to its frequency, forming the foundation of quantum theory.","symbol":"h","value":"6.62607015e-34","unit":"J*s","images":[]}',
         3, ARRAY['concept', 'constants']),
        ('physics', 'Gravitational Constant',
         '{"description":"The constant determining the strength of gravitational attraction","category":"Constants & Units","difficulty":3,"popularity":85,"group":"Physical Constants","primary_val":"G","secondary_val":"6.674×10^(−11) m^3*kg^(−1)*s^(−2)","definition":"The gravitational constant G appears in Newton''s law of universal gravitation, determining the force between masses.","symbol":"G","value":"6.67430e-11","unit":"m^3*kg^(-1)*s^(-2)","images":[]}',
         3, ARRAY['concept', 'constants']),
        ('physics', 'Avogadro''s Number',
         '{"description":"The number of constituent particles in one mole of a substance","category":"Constants & Units","difficulty":2,"popularity":85,"group":"Physical Constants","primary_val":"N_A","secondary_val":"6.022×10^(23) mol^(−1)","definition":"Avogadro''s number defines the number of atoms, molecules, or ions in one mole of any substance.","symbol":"N_A","value":"6.02214076e23","unit":"mol^(-1)","images":[]}',
         2, ARRAY['concept', 'constants']),
        ('physics', 'Boltzmann Constant',
         '{"description":"The constant relating temperature to thermal energy","category":"Constants & Units","difficulty":3,"popularity":75,"group":"Physical Constants","primary_val":"k_B","secondary_val":"1.381×10^(−23) J/K","definition":"The Boltzmann constant connects the average kinetic energy of particles in a gas to the absolute temperature.","symbol":"k_B","value":"1.380649e-23","unit":"J/K","images":[]}',
         3, ARRAY['concept', 'constants']),
        ('physics', 'Universal Gas Constant',
         '{"description":"The constant relating energy scale to temperature in the ideal gas law","category":"Constants & Units","difficulty":2,"popularity":75,"group":"Physical Constants","primary_val":"R","secondary_val":"8.314 J/(mol*K)","definition":"The gas constant is the proportionality constant in the ideal gas law, equivalent to Boltzmann constant times Avogadro''s number.","symbol":"R","value":"8.314462618","unit":"J/(mol*K)","images":[]}',
         2, ARRAY['concept', 'constants']),
        ('physics', 'Electron Volt',
         '{"description":"The energy gained by an electron accelerated through one volt","category":"Constants & Units","difficulty":2,"popularity":80,"group":"Physical Constants","primary_val":"eV","secondary_val":"1.602×10^(−19) J","definition":"An electron volt is a unit of energy commonly used in atomic, nuclear, and particle physics.","symbol":"eV","value":"1.602176634e-19","unit":"J","images":[]}',
         2, ARRAY['concept', 'constants']),
        ('physics', 'Coulomb''s Constant',
         '{"description":"The constant in Coulomb''s law for electric force between charges","category":"Constants & Units","difficulty":3,"popularity":70,"group":"Physical Constants","primary_val":"k_e","secondary_val":"8.988×10^9 N*m^2/C^2","definition":"Coulomb''s constant determines the strength of electrostatic force between two point charges.","symbol":"k_e","value":"8.9875517923e9","unit":"N*m^2/C^2","images":[]}',
         3, ARRAY['concept', 'constants']),
        ('physics', 'Stefan-Boltzmann Constant',
         '{"description":"The constant relating blackbody radiation to temperature","category":"Constants & Units","difficulty":4,"popularity":65,"group":"Physical Constants","primary_val":"σ","secondary_val":"5.670×10^(−8) W*m^(−2)*K^(−4)","definition":"The Stefan-Boltzmann constant determines the total power radiated per unit area by a blackbody as a function of temperature.","symbol":"σ","value":"5.670374419e-8","unit":"W*m^(-2)*K^(-4)","images":[]}',
         4, ARRAY['concept', 'constants']),
        ('physics', 'Fine-Structure Constant',
         '{"description":"A dimensionless constant characterizing electromagnetic interaction strength","category":"Constants & Units","difficulty":4,"popularity":65,"group":"Physical Constants","primary_val":"α","secondary_val":"≈ 1/137","definition":"The fine-structure constant is a fundamental dimensionless constant that determines the strength of electromagnetic interactions.","symbol":"α","value":"0.0072973525693","images":[]}',
         4, ARRAY['concept', 'constants']),

        -- ═══════════════════════════════════════════════════════════
        -- FAMOUS PHYSICISTS (12) — Class A (Persons)
        -- ═══════════════════════════════════════════════════════════
        ('physics', 'Isaac Newton',
         '{"description":"English physicist who formulated the laws of motion and universal gravitation","category":"Physicist","difficulty":2,"popularity":100,"birth_year":1643,"death_year":1727,"nationality":"English","achievement":"Laws of motion and universal gravitation","famous_for":"Newton''s laws of motion and calculus","definition":"Isaac Newton revolutionized physics with his three laws of motion, theory of gravity, and development of calculus.","images":[]}',
         2, ARRAY['person', 'physics']),
        ('physics', 'Albert Einstein',
         '{"description":"German-born physicist who developed the theory of relativity","category":"Physicist","difficulty":2,"popularity":100,"birth_year":1879,"death_year":1955,"nationality":"German","achievement":"Theory of relativity and E = mc^2","famous_for":"Theory of relativity and E = mc^2","definition":"Albert Einstein transformed modern physics with his special and general theories of relativity and quantum contributions.","images":[]}',
         2, ARRAY['person', 'physics']),
        ('physics', 'Niels Bohr',
         '{"description":"Danish physicist who pioneered quantum atomic theory","category":"Physicist","difficulty":3,"popularity":85,"birth_year":1885,"death_year":1962,"nationality":"Danish","achievement":"Bohr model of the atom","famous_for":"Bohr model and quantum atomic structure","definition":"Niels Bohr developed the planetary model of the atom with quantized electron orbits and founded quantum theory.","images":[]}',
         3, ARRAY['person', 'physics']),
        ('physics', 'Marie Curie',
         '{"description":"Polish-French physicist who pioneered radioactivity research","category":"Physicist","difficulty":2,"popularity":95,"birth_year":1867,"death_year":1934,"nationality":"Polish-French","achievement":"Discovery of radium and polonium","famous_for":"Pioneering radioactivity research","definition":"Marie Curie discovered radium and polonium, coined the term radioactivity, and won two Nobel Prizes.","images":[]}',
         2, ARRAY['person', 'physics']),
        ('physics', 'Richard Feynman',
         '{"description":"American physicist known for quantum electrodynamics","category":"Physicist","difficulty":3,"popularity":85,"birth_year":1918,"death_year":1988,"nationality":"American","achievement":"Quantum electrodynamics (QED)","famous_for":"Feynman diagrams and quantum electrodynamics","definition":"Richard Feynman revolutionized quantum electrodynamics with his diagrammatic approach and path integral formulation.","images":[]}',
         3, ARRAY['person', 'physics']),
        ('physics', 'Galileo Galilei',
         '{"description":"Italian astronomer and physicist, father of modern science","category":"Physicist","difficulty":2,"popularity":90,"birth_year":1564,"death_year":1642,"nationality":"Italian","achievement":"Pioneered experimental physics and telescopic astronomy","famous_for":"Astronomical observations and laws of motion","definition":"Galileo pioneered the experimental scientific method, improved the telescope, and discovered Jupiter''s moons.","images":[]}',
         2, ARRAY['person', 'physics']),
        ('physics', 'Nikola Tesla',
         '{"description":"Serbian-American inventor and electrical engineer","category":"Physicist","difficulty":2,"popularity":95,"birth_year":1856,"death_year":1943,"nationality":"Serbian-American","achievement":"Alternating current electrical system","famous_for":"AC electricity and the Tesla coil","definition":"Nikola Tesla invented the alternating current electrical system, the Tesla coil, and pioneered wireless energy transmission.","images":[]}',
         2, ARRAY['person', 'physics']),
        ('physics', 'James Clerk Maxwell',
         '{"description":"Scottish physicist who unified electricity and magnetism","category":"Physicist","difficulty":3,"popularity":85,"birth_year":1831,"death_year":1879,"nationality":"Scottish","achievement":"Maxwell''s equations of electromagnetism","famous_for":"Maxwell''s equations unifying electricity and magnetism","definition":"James Clerk Maxwell formulated the set of equations describing electromagnetic fields and predicted electromagnetic waves.","images":[]}',
         3, ARRAY['person', 'physics']),
        ('physics', 'Michael Faraday',
         '{"description":"English scientist who discovered electromagnetic induction","category":"Physicist","difficulty":2,"popularity":85,"birth_year":1791,"death_year":1867,"nationality":"English","achievement":"Electromagnetic induction","famous_for":"Faraday''s law of induction","definition":"Michael Faraday discovered electromagnetic induction, diamagnetism, and electrolysis, despite minimal formal education.","images":[]}',
         2, ARRAY['person', 'physics']),
        ('physics', 'Stephen Hawking',
         '{"description":"English theoretical physicist who studied black holes and cosmology","category":"Physicist","difficulty":3,"popularity":90,"birth_year":1942,"death_year":2018,"nationality":"English","achievement":"Hawking radiation from black holes","famous_for":"Hawking radiation and black hole thermodynamics","definition":"Stephen Hawking proposed that black holes emit radiation (Hawking radiation) and wrote the bestselling A Brief History of Time.","images":[]}',
         3, ARRAY['person', 'physics']),
        ('physics', 'Erwin Schrödinger',
         '{"description":"Austrian physicist who developed wave mechanics","category":"Physicist","difficulty":3,"popularity":85,"birth_year":1887,"death_year":1961,"nationality":"Austrian","achievement":"Schrödinger equation","famous_for":"Schrödinger''s cat thought experiment","definition":"Erwin Schrödinger formulated the fundamental equation of quantum mechanics and the famous cat paradox thought experiment.","images":[]}',
         3, ARRAY['person', 'physics']),
        ('physics', 'Max Planck',
         '{"description":"German physicist who founded quantum theory","category":"Physicist","difficulty":3,"popularity":85,"birth_year":1858,"death_year":1947,"nationality":"German","achievement":"Quantum theory and Planck''s constant","famous_for":"Originator of quantum theory","definition":"Max Planck introduced the concept of energy quanta and Planck''s constant, founding the field of quantum mechanics.","images":[]}',
         3, ARRAY['person', 'physics']);

    END IF;
END $$;
