-- ===================================================================
-- Migration: seed 200 biology entities
-- Schema per PROCEDURAL_ENTITY_RULES.md — biology concepts use
-- Class B (Facts/Concepts), famous biologists use Class A (Persons).
-- ===================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM wordup_entities WHERE type = 'biology' LIMIT 1) THEN

        -- ═══════════════════════════════════════════════════════════
        -- CELL BIOLOGY (18)
        -- ═══════════════════════════════════════════════════════════
        INSERT INTO wordup_entities (type, label, metadata, difficulty, tags) VALUES
        ('biology', 'Cell',
         '{"description":"The basic structural and functional unit of all living organisms","category":"Cell Biology","difficulty":1,"popularity":95,"group":"Cell Biology","primary_val":"—","secondary_val":"—","definition":"A cell is the smallest unit of life that can replicate independently, forming the building block of all living tissues.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Cell Membrane',
         '{"description":"A phospholipid bilayer that surrounds and protects the cell","category":"Cell Biology","difficulty":1,"popularity":90,"group":"Cell Biology","primary_val":"—","secondary_val":"Selectively permeable","definition":"The cell membrane regulates the passage of substances in and out of the cell, maintaining internal homeostasis.","contrast":"Cell Wall","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Nucleus',
         '{"description":"The membrane-bound organelle containing the cell''s genetic material","category":"Cell Biology","difficulty":1,"popularity":95,"group":"Cell Biology","primary_val":"—","secondary_val":"Contains DNA","definition":"The nucleus houses chromosomes and controls gene expression, replication, and overall cellular activities.","contrast":"Nucleolus","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Mitochondria',
         '{"description":"The powerhouse organelle that generates ATP through cellular respiration","category":"Cell Biology","difficulty":1,"popularity":95,"group":"Cell Biology","primary_val":"—","secondary_val":"Double membrane","definition":"Mitochondria convert chemical energy from food into ATP via oxidative phosphorylation, powering cellular processes.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Ribosome',
         '{"description":"A molecular machine that synthesizes proteins from amino acids","category":"Cell Biology","difficulty":2,"popularity":85,"group":"Cell Biology","primary_val":"—","secondary_val":"rRNA + proteins","definition":"Ribosomes translate messenger RNA into polypeptide chains, found free in cytoplasm or bound to the rough ER.","contrast":"Lysosome","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Endoplasmic Reticulum',
         '{"description":"A membrane network involved in protein and lipid synthesis","category":"Cell Biology","difficulty":2,"popularity":80,"group":"Cell Biology","primary_val":"ER","secondary_val":"Rough or smooth","definition":"The endoplasmic reticulum processes proteins (rough ER with ribosomes) and synthesizes lipids (smooth ER).","contrast":"Golgi Apparatus","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Golgi Apparatus',
         '{"description":"An organelle that modifies, sorts, and packages proteins for transport","category":"Cell Biology","difficulty":2,"popularity":80,"group":"Cell Biology","primary_val":"—","secondary_val":"Stacked cisternae","definition":"The Golgi apparatus modifies proteins from the ER and directs them to their final destinations inside or outside the cell.","contrast":"Endoplasmic Reticulum","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Lysosome',
         '{"description":"A membrane-bound organelle containing digestive enzymes","category":"Cell Biology","difficulty":2,"popularity":80,"group":"Cell Biology","primary_val":"—","secondary_val":"Acidic pH","definition":"Lysosomes break down waste materials, cellular debris, and foreign invaders through enzymatic digestion.","contrast":"Ribosome","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Cytoplasm',
         '{"description":"The gel-like substance filling the cell between the membrane and nucleus","category":"Cell Biology","difficulty":1,"popularity":80,"group":"Cell Biology","primary_val":"—","secondary_val":"—","definition":"Cytoplasm is the aqueous medium that suspends organelles and facilitates intracellular transport and metabolic reactions.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Chloroplast',
         '{"description":"An organelle in plant cells that performs photosynthesis","category":"Cell Biology","difficulty":2,"popularity":90,"group":"Cell Biology","primary_val":"—","secondary_val":"Contains chlorophyll","definition":"Chloroplasts convert light energy into chemical energy through photosynthesis, producing glucose and oxygen.","contrast":"Mitochondria","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Cell Wall',
         '{"description":"A rigid outer layer providing structural support to plant cells","category":"Cell Biology","difficulty":1,"popularity":80,"group":"Cell Biology","primary_val":"—","secondary_val":"Cellulose","definition":"The cell wall surrounds the cell membrane of plants, providing mechanical strength and protection against osmotic pressure.","contrast":"Cell Membrane","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Vacuole',
         '{"description":"A membrane-bound organelle for storage of water, nutrients, and waste","category":"Cell Biology","difficulty":1,"popularity":75,"group":"Cell Biology","primary_val":"—","secondary_val":"Central in plants","definition":"Vacuoles store water, ions, and nutrients and maintain turgor pressure in plant cells for structural rigidity.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Prokaryotic Cell',
         '{"description":"A simple cell lacking a nucleus and membrane-bound organelles","category":"Cell Biology","difficulty":2,"popularity":85,"group":"Cell Biology","primary_val":"—","secondary_val":"No nucleus","definition":"Prokaryotic cells are smaller and simpler than eukaryotes, with genetic material free in the nucleoid region.","example":"Bacteria and archaea","contrast":"Eukaryotic Cell","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Eukaryotic Cell',
         '{"description":"A complex cell with a nucleus and membrane-bound organelles","category":"Cell Biology","difficulty":2,"popularity":85,"group":"Cell Biology","primary_val":"—","secondary_val":"Has nucleus","definition":"Eukaryotic cells are larger and more complex, compartmentalizing functions within specialized membrane-bound organelles.","example":"Animal and plant cells","contrast":"Prokaryotic Cell","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Organelle',
         '{"description":"A specialized subunit within a cell that performs a specific function","category":"Cell Biology","difficulty":2,"popularity":80,"group":"Cell Biology","primary_val":"—","secondary_val":"—","definition":"Organelles are membrane-bound structures within eukaryotic cells that compartmentalize distinct biochemical processes.","example":"Mitochondria, nucleus, ER, Golgi","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Cytoskeleton',
         '{"description":"A network of protein filaments maintaining cell shape and enabling movement","category":"Cell Biology","difficulty":3,"popularity":70,"group":"Cell Biology","primary_val":"—","secondary_val":"—","definition":"The cytoskeleton provides structural support, facilitates cell division, and enables intracellular transport and cell motility.","example":"Microtubules, actin filaments, intermediate filaments","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Centriole',
         '{"description":"A cylindrical organelle involved in cell division and spindle formation","category":"Cell Biology","difficulty":3,"popularity":65,"group":"Cell Biology","primary_val":"—","secondary_val":"9 triplets of microtubules","definition":"Centrioles organize the mitotic spindle during cell division and form the base of cilia and flagella.","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Nucleolus',
         '{"description":"A dense region within the nucleus responsible for ribosome assembly","category":"Cell Biology","difficulty":3,"popularity":65,"group":"Cell Biology","primary_val":"—","secondary_val":"rRNA synthesis","definition":"The nucleolus produces ribosomal RNA and assembles ribosome subunits for protein synthesis.","contrast":"Nucleus","images":[]}',
         3, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- GENETICS & DNA (17)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Gene',
         '{"description":"A segment of DNA that codes for a functional product, typically a protein","category":"Genetics","difficulty":1,"popularity":95,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"A gene is the fundamental unit of heredity, carrying instructions for building and maintaining an organism.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Chromosome',
         '{"description":"A thread-like structure of DNA and proteins carrying genetic information","category":"Genetics","difficulty":1,"popularity":90,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"Chromosomes are tightly coiled DNA molecules that organize and protect genetic material during cell division.","example":"Humans have 46 chromosomes in 23 pairs","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Genome',
         '{"description":"The complete set of genetic material present in an organism","category":"Genetics","difficulty":2,"popularity":85,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"The genome encompasses all DNA sequences, including coding genes and noncoding regions, of an organism.","example":"The human genome contains about 3 billion base pairs","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Allele',
         '{"description":"An alternative form of a gene occupying the same position on homologous chromosomes","category":"Genetics","difficulty":2,"popularity":85,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"Alleles are variant versions of a gene that can produce different traits, inherited from each parent.","example":"Blue vs. brown eye color alleles","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Genotype',
         '{"description":"The genetic constitution of an organism representing its allele combination","category":"Genetics","difficulty":2,"popularity":85,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"Genotype refers to the specific set of alleles an individual carries for a particular gene or trait.","contrast":"Phenotype","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Phenotype',
         '{"description":"The observable physical or biochemical characteristics of an organism","category":"Genetics","difficulty":2,"popularity":85,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"Phenotype results from the interaction of genotype with the environment, including appearance, behavior, and biochemistry.","contrast":"Genotype","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Mutation',
         '{"description":"A change in the DNA sequence that may alter gene function","category":"Genetics","difficulty":2,"popularity":90,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"Mutations are permanent changes in DNA that can be neutral, harmful, or beneficial to the organism.","example":"Point mutations, insertions, deletions, duplications","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'DNA Replication',
         '{"description":"The process of copying DNA to produce two identical molecules","category":"Genetics","difficulty":3,"popularity":90,"group":"Genetics","primary_val":"—","secondary_val":"Semiconservative","definition":"DNA replication unwinds the double helix and synthesizes new strands complementary to each original template strand.","contrast":"Transcription","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Transcription',
         '{"description":"The synthesis of RNA from a DNA template","category":"Genetics","difficulty":3,"popularity":90,"group":"Genetics","primary_val":"DNA → mRNA","secondary_val":"—","definition":"Transcription copies a gene''s DNA sequence into messenger RNA, which carries the genetic code to ribosomes.","contrast":"Translation","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Translation',
         '{"description":"The process of protein synthesis using mRNA as a template","category":"Genetics","difficulty":3,"popularity":90,"group":"Genetics","primary_val":"mRNA → Protein","secondary_val":"—","definition":"Translation decodes mRNA codons at the ribosome to assemble amino acids into a polypeptide chain.","contrast":"Transcription","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Codon',
         '{"description":"A sequence of three nucleotides that specifies a particular amino acid","category":"Genetics","difficulty":3,"popularity":80,"group":"Genetics","primary_val":"—","secondary_val":"3 nucleotides","definition":"Codons are the basic units of the genetic code, with each triplet of mRNA bases corresponding to one amino acid or stop signal.","example":"AUG codes for methionine and is the start codon","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Genetic Code',
         '{"description":"The set of rules by which nucleotide sequences encode proteins","category":"Genetics","difficulty":3,"popularity":85,"group":"Genetics","primary_val":"—","secondary_val":"64 codons, 20 amino acids","definition":"The genetic code maps each three-nucleotide codon to a specific amino acid, with redundancy across multiple codons for the same amino acid.","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Dominant Trait',
         '{"description":"A trait that is expressed when at least one dominant allele is present","category":"Genetics","difficulty":2,"popularity":85,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"A dominant trait masks the effect of a recessive allele and appears in the phenotype of heterozygotes.","example":"Brown eyes, dimples, widows peak","contrast":"Recessive Trait","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Recessive Trait',
         '{"description":"A trait that is expressed only when two recessive alleles are present","category":"Genetics","difficulty":2,"popularity":85,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"A recessive trait requires two copies of the recessive allele to be expressed in the phenotype.","example":"Blue eyes, attached earlobes","contrast":"Dominant Trait","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Heredity',
         '{"description":"The passing of genetic traits from parents to offspring","category":"Genetics","difficulty":1,"popularity":90,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"Heredity is the transmission of genes from one generation to the next, explaining family resemblance and variation.","famous_for":"Mendel''s laws of inheritance","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Crossing Over',
         '{"description":"The exchange of genetic material between homologous chromosomes during meiosis","category":"Genetics","difficulty":3,"popularity":80,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"Crossing over during prophase I of meiosis increases genetic diversity by swapping DNA segments between paired chromosomes.","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Karyotype',
         '{"description":"A visual display of an individual''s complete set of chromosomes","category":"Genetics","difficulty":2,"popularity":75,"group":"Genetics","primary_val":"—","secondary_val":"—","definition":"A karyotype arranges chromosomes by size and banding pattern to detect abnormalities in number or structure.","example":"Trisomy 21 shows three copies of chromosome 21","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- EVOLUTION (14)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Natural Selection',
         '{"description":"The process by which organisms better adapted to their environment survive and reproduce more","category":"Evolution","difficulty":2,"popularity":95,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Natural selection drives evolution by favoring individuals with advantageous traits that enhance survival and reproductive success.","famous_for":"Darwin''s theory of evolution by natural selection","contrast":"Artificial Selection","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Evolution',
         '{"description":"The change in inherited characteristics of populations over successive generations","category":"Evolution","difficulty":2,"popularity":95,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Evolution is the central organizing principle of biology explaining the diversity and adaptation of life over time.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Adaptation',
         '{"description":"A trait that enhances an organism''s ability to survive in its environment","category":"Evolution","difficulty":2,"popularity":90,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Adaptations are inherited features that improve fitness, arising through natural selection over many generations.","example":"Camouflage, beak shape, drought resistance","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Genetic Drift',
         '{"description":"Random changes in allele frequencies due to chance events in small populations","category":"Evolution","difficulty":3,"popularity":80,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Genetic drift causes random fluctuations in gene frequency, having a stronger effect in small populations.","contrast":"Gene Flow","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Gene Flow',
         '{"description":"The transfer of genetic material between populations through migration","category":"Evolution","difficulty":3,"popularity":75,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Gene flow introduces new alleles into a population when individuals migrate and interbreed between populations.","contrast":"Genetic Drift","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Speciation',
         '{"description":"The formation of new and distinct species through evolutionary processes","category":"Evolution","difficulty":3,"popularity":85,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Speciation occurs when populations become reproductively isolated and diverge genetically over time.","example":"Darwin''s finches speciating across Galapagos islands","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Common Ancestor',
         '{"description":"An ancestral organism from which two or more descendant lineages diverged","category":"Evolution","difficulty":2,"popularity":85,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"A common ancestor is a shared evolutionary origin point from which different species inherited their features.","example":"All tetrapods share a common fish ancestor","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Biological Fitness',
         '{"description":"The ability of an organism to survive and reproduce in its environment","category":"Evolution","difficulty":2,"popularity":80,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Fitness measures how well an organism is adapted to its environment, determined by its reproductive success relative to others.","contrast":"Adaptation","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Convergent Evolution',
         '{"description":"The independent evolution of similar traits in unrelated species","category":"Evolution","difficulty":3,"popularity":80,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Convergent evolution produces analogous structures in different lineages adapting to similar environmental pressures.","example":"Wings in birds, bats, and insects","contrast":"Divergent Evolution","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Divergent Evolution',
         '{"description":"The accumulation of differences between related species over time","category":"Evolution","difficulty":3,"popularity":75,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Divergent evolution causes related populations to become increasingly different as they adapt to distinct environments.","example":"Darwin''s finches evolving different beak shapes","contrast":"Convergent Evolution","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Extinction',
         '{"description":"The permanent loss of a species from Earth","category":"Evolution","difficulty":2,"popularity":85,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Extinction occurs when a species cannot adapt to changing conditions and all its members die out.","example":"Dinosaur extinction at the K-Pg boundary","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Vestigial Structure',
         '{"description":"A reduced or functionless structure that was functional in an ancestor","category":"Evolution","difficulty":2,"popularity":75,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Vestigial structures provide evidence for evolution by showing remnants of organs that served a purpose in ancestral species.","example":"Human appendix, whale pelvic bones","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Sexual Selection',
         '{"description":"A form of natural selection based on mate choice and competition for mates","category":"Evolution","difficulty":3,"popularity":80,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Sexual selection favors traits that increase mating success, sometimes at odds with survival selection.","example":"Peacock''s elaborate tail feathers","contrast":"Natural Selection","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Artificial Selection',
         '{"description":"The intentional breeding of organisms for desired traits by humans","category":"Evolution","difficulty":2,"popularity":80,"group":"Evolution","primary_val":"—","secondary_val":"—","definition":"Artificial selection or selective breeding modifies species over generations by choosing which individuals reproduce.","example":"Domestication of wolves into dog breeds","contrast":"Natural Selection","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- ECOLOGY (18)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Ecosystem',
         '{"description":"A community of organisms interacting with their physical environment","category":"Ecology","difficulty":1,"popularity":95,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"An ecosystem includes all living organisms in an area together with nonliving components like air, water, and soil.","example":"A forest, coral reef, or desert ecosystem","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Habitat',
         '{"description":"The natural environment where an organism lives and thrives","category":"Ecology","difficulty":1,"popularity":85,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"A habitat provides the food, shelter, water, and space that a particular species needs to survive.","example":"A pond is a habitat for frogs and aquatic plants","contrast":"Ecological Niche","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Ecological Niche',
         '{"description":"The role and position a species occupies in its environment","category":"Ecology","difficulty":2,"popularity":80,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"A niche encompasses how a species obtains resources, interacts with others, and contributes to ecosystem function.","contrast":"Habitat","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Food Chain',
         '{"description":"A linear sequence of organisms where each consumes the one below","category":"Ecology","difficulty":1,"popularity":90,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"A food chain traces energy flow from producers to consumers to decomposers in an ecosystem.","example":"Grass → Grasshopper → Frog → Snake → Hawk","contrast":"Food Web","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Food Web',
         '{"description":"A complex network of interconnected food chains in an ecosystem","category":"Ecology","difficulty":2,"popularity":90,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"A food web represents the many feeding relationships in a community, showing how energy moves through the ecosystem.","contrast":"Food Chain","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Biome',
         '{"description":"A large geographic region with similar climate and characteristic communities","category":"Ecology","difficulty":2,"popularity":85,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"Biomes are major life zones defined by vegetation type and climate, such as tropical rainforests, tundra, and deserts.","example":"The Amazon rainforest, Siberian tundra, Sahara desert","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Population',
         '{"description":"A group of individuals of the same species living in a particular area","category":"Ecology","difficulty":1,"popularity":85,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"A population is the basic unit of ecology — a group of interbreeding organisms of one species in a defined location.","contrast":"Community","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Community',
         '{"description":"All populations of different species living and interacting in an area","category":"Ecology","difficulty":1,"popularity":80,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"A community includes all the various organisms in an ecosystem that interact through predation, competition, and symbiosis.","contrast":"Population","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Biodiversity',
         '{"description":"The variety of life forms within a given ecosystem, biome, or planet","category":"Ecology","difficulty":2,"popularity":90,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"Biodiversity encompasses species diversity, genetic diversity, and ecosystem diversity, crucial for ecosystem resilience.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Producer',
         '{"description":"An organism that makes its own food from sunlight or chemical energy","category":"Ecology","difficulty":1,"popularity":85,"group":"Ecology","primary_val":"—","secondary_val":"Autotrophic","definition":"Producers or autotrophs form the base of the food chain by converting energy into organic compounds.","example":"Plants, algae, phytoplankton","contrast":"Consumer","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Consumer',
         '{"description":"An organism that obtains energy by feeding on other organisms","category":"Ecology","difficulty":1,"popularity":85,"group":"Ecology","primary_val":"—","secondary_val":"Heterotrophic","definition":"Consumers cannot produce their own food and rely on consuming producers or other consumers for energy.","example":"Herbivores, carnivores, omnivores","contrast":"Producer","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Decomposer',
         '{"description":"An organism that breaks down dead matter, recycling nutrients","category":"Ecology","difficulty":1,"popularity":80,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"Decomposers break down organic waste and dead organisms, returning essential nutrients to the soil and ecosystem.","example":"Bacteria, fungi, earthworms","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Symbiosis',
         '{"description":"A close, long-term interaction between two different species","category":"Ecology","difficulty":2,"popularity":90,"group":"Ecology","primary_val":"—","secondary_val":"—","definition":"Symbiosis describes intimate relationships between species, which can be mutualistic, commensal, or parasitic.","example":"Clownfish and sea anemone mutualism","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Mutualism',
         '{"description":"A symbiotic relationship benefiting both participating species","category":"Ecology","difficulty":2,"popularity":85,"group":"Ecology","primary_val":"—","secondary_val":"+/+","definition":"Mutualism is a win-win interaction where both species gain benefits, such as pollination or nutrient exchange.","example":"Bees pollinating flowers while collecting nectar","contrast":"Parasitism","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Parasitism',
         '{"description":"A symbiotic relationship where one species benefits at the expense of the other","category":"Ecology","difficulty":2,"popularity":80,"group":"Ecology","primary_val":"—","secondary_val":"+/−","definition":"Parasitism benefits the parasite while harming the host, often without immediately killing it.","example":"Tapeworms in the intestines of mammals","contrast":"Mutualism","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Commensalism',
         '{"description":"A symbiotic relationship benefiting one species while the other is unaffected","category":"Ecology","difficulty":2,"popularity":75,"group":"Ecology","primary_val":"—","secondary_val":"+/0","definition":"Commensalism helps one species without affecting the other, such as barnacles attaching to whales.","example":"Birds nesting in trees","contrast":"Mutualism","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Predation',
         '{"description":"An interaction where one organism kills and consumes another","category":"Ecology","difficulty":1,"popularity":85,"group":"Ecology","primary_val":"—","secondary_val":"+/−","definition":"Predation is a fundamental ecological interaction regulating populations and driving evolutionary adaptations.","example":"Lion hunting zebra, spider catching insects","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Carrying Capacity',
         '{"description":"The maximum population size an environment can sustain indefinitely","category":"Ecology","difficulty":3,"popularity":80,"group":"Ecology","primary_val":"K","secondary_val":"—","definition":"Carrying capacity is determined by available resources and limits population growth in an ecosystem.","symbol":"K","images":[]}',
         3, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- HUMAN ANATOMY — SYSTEMS (18)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Heart',
         '{"description":"A muscular organ that pumps blood throughout the circulatory system","category":"Human Anatomy","difficulty":1,"popularity":95,"group":"Human Anatomy","primary_val":"—","secondary_val":"4 chambers","definition":"The heart pumps oxygenated blood to the body and deoxygenated blood to the lungs through rhythmic contractions.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Lung',
         '{"description":"A respiratory organ responsible for gas exchange with the environment","category":"Human Anatomy","difficulty":1,"popularity":90,"group":"Human Anatomy","primary_val":"—","secondary_val":"2 lobes (left), 3 lobes (right)","definition":"Lungs extract oxygen from inhaled air and release carbon dioxide through millions of tiny air sacs called alveoli.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Brain',
         '{"description":"The central organ of the nervous system controlling thought, memory, and body functions","category":"Human Anatomy","difficulty":1,"popularity":95,"group":"Human Anatomy","primary_val":"—","secondary_val":"~1.4 kg","definition":"The brain processes sensory information, coordinates movement, regulates homeostasis, and enables consciousness.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Liver',
         '{"description":"A large organ involved in metabolism, detoxification, and nutrient storage","category":"Human Anatomy","difficulty":2,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"Largest internal organ","definition":"The liver processes nutrients, produces bile, detoxifies harmful substances, and regulates blood sugar levels.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Kidney',
         '{"description":"An organ that filters blood and produces urine to maintain fluid balance","category":"Human Anatomy","difficulty":2,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"Bean-shaped","definition":"Kidneys filter waste from blood, regulate electrolyte balance, and produce urine for excretion.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Stomach',
         '{"description":"A digestive organ that breaks down food using acid and enzymes","category":"Human Anatomy","difficulty":1,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"Holds ~1 liter","definition":"The stomach churns food and secretes hydrochloric acid and pepsin to begin protein digestion.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Pancreas',
         '{"description":"A glandular organ that produces digestive enzymes and insulin","category":"Human Anatomy","difficulty":2,"popularity":80,"group":"Human Anatomy","primary_val":"—","secondary_val":"Both endocrine and exocrine","definition":"The pancreas secretes enzymes into the small intestine for digestion and releases insulin to regulate blood sugar.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Spleen',
         '{"description":"An organ that filters blood, recycles red blood cells, and supports immunity","category":"Human Anatomy","difficulty":2,"popularity":70,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"The spleen removes old red blood cells, stores platelets, and produces lymphocytes for immune defense.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Skin',
         '{"description":"The largest organ providing a protective barrier against the environment","category":"Human Anatomy","difficulty":1,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"~2 m^2 surface area","definition":"Skin protects against pathogens, regulates temperature, and provides sensory information about touch and temperature.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Skeleton',
         '{"description":"The internal framework of bones supporting the body and protecting organs","category":"Human Anatomy","difficulty":1,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"206 bones in adults","definition":"The skeleton provides structure, enables movement, stores minerals, and produces blood cells in bone marrow.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Muscle',
         '{"description":"A tissue capable of contracting to produce movement and force","category":"Human Anatomy","difficulty":1,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"3 types","definition":"Muscles generate force for movement, maintain posture, pump blood, and produce heat through contraction.","example":"Skeletal, smooth, and cardiac muscle","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Neuron',
         '{"description":"A specialized cell transmitting electrical and chemical signals in the nervous system","category":"Human Anatomy","difficulty":2,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"Neurons communicate via electrical impulses and neurotransmitters, forming the basic unit of the nervous system.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Circulatory System',
         '{"description":"The organs and vessels that transport blood throughout the body","category":"Human Anatomy","difficulty":1,"popularity":90,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"The circulatory system delivers oxygen and nutrients to tissues and removes waste products via the heart and blood vessels.","example":"Heart, arteries, veins, capillaries","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Respiratory System',
         '{"description":"The set of organs facilitating gas exchange with the environment","category":"Human Anatomy","difficulty":1,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"The respiratory system brings oxygen into the body and expels carbon dioxide through breathing.","example":"Nasal cavity, trachea, bronchi, lungs","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Digestive System',
         '{"description":"The organs that break down food and absorb nutrients","category":"Human Anatomy","difficulty":1,"popularity":85,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"The digestive system processes food from ingestion through mechanical and chemical digestion to absorption and elimination.","example":"Mouth, esophagus, stomach, intestines","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Nervous System',
         '{"description":"The network of nerve cells that coordinates actions and sensory information","category":"Human Anatomy","difficulty":2,"popularity":90,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"The nervous system detects stimuli, processes information, and directs responses through the brain, spinal cord, and nerves.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Endocrine System',
         '{"description":"The network of glands that produce and secrete hormones","category":"Human Anatomy","difficulty":2,"popularity":80,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"The endocrine system regulates growth, metabolism, reproduction, and homeostasis through hormone signaling.","example":"Pituitary, thyroid, adrenal glands","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Immune System',
         '{"description":"The body''s defense system against pathogens and foreign substances","category":"Human Anatomy","difficulty":2,"popularity":90,"group":"Human Anatomy","primary_val":"—","secondary_val":"—","definition":"The immune system protects the body through physical barriers, innate responses, and adaptive immunity with memory.","example":"White blood cells, antibodies, lymph nodes","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- TISSUES & FLUIDS (12)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Blood',
         '{"description":"A connective tissue that transports oxygen, nutrients, and waste throughout the body","category":"Tissues & Fluids","difficulty":1,"popularity":90,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"~5 liters in adults","definition":"Blood consists of red blood cells, white blood cells, platelets, and plasma delivering essential substances.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Bone',
         '{"description":"A rigid connective tissue forming the skeleton","category":"Tissues & Fluids","difficulty":1,"popularity":85,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"—","definition":"Bone is a living tissue composed of collagen and calcium phosphate, continuously remodeled throughout life.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Cartilage',
         '{"description":"A flexible connective tissue cushioning joints and supporting structures","category":"Tissues & Fluids","difficulty":2,"popularity":75,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"—","definition":"Cartilage provides flexible support and reduces friction between bones in joints without blood vessels.","contrast":"Bone","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Muscle Tissue',
         '{"description":"A specialized tissue capable of contraction for movement and force generation","category":"Tissues & Fluids","difficulty":2,"popularity":80,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"3 types","definition":"Muscle tissue includes skeletal, smooth, and cardiac types, each adapted for different functions.","example":"Biceps, heart muscle, intestinal walls","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Nervous Tissue',
         '{"description":"Tissue specialized for transmitting electrical impulses","category":"Tissues & Fluids","difficulty":2,"popularity":80,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"—","definition":"Nervous tissue consists of neurons for signal transmission and glial cells for support and insulation.","example":"Brain, spinal cord, peripheral nerves","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Connective Tissue',
         '{"description":"Tissue that supports, binds, and connects other tissues and organs","category":"Tissues & Fluids","difficulty":2,"popularity":70,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"—","definition":"Connective tissue includes bone, blood, cartilage, fat, and fibrous tissues that provide structural support.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Epithelial Tissue',
         '{"description":"Tissue that forms linings, coverings, and glands of the body","category":"Tissues & Fluids","difficulty":2,"popularity":70,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"—","definition":"Epithelial tissue covers body surfaces, lines cavities, and secretes substances for protection and absorption.","example":"Skin epidermis, intestinal lining","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Artery',
         '{"description":"A blood vessel carrying blood away from the heart","category":"Tissues & Fluids","difficulty":2,"popularity":80,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"Thick muscular walls","definition":"Arteries transport oxygenated blood at high pressure from the heart to the body''s tissues.","contrast":"Vein","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Vein',
         '{"description":"A blood vessel carrying blood toward the heart","category":"Tissues & Fluids","difficulty":2,"popularity":80,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"Has valves","definition":"Veins return deoxygenated blood to the heart under low pressure, using one-way valves to prevent backflow.","contrast":"Artery","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Capillary',
         '{"description":"The smallest blood vessel where gas and nutrient exchange occurs","category":"Tissues & Fluids","difficulty":2,"popularity":80,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"One cell thick","definition":"Capillaries connect arteries and veins, with thin walls allowing exchange of oxygen, CO_2, and nutrients.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Lymph',
         '{"description":"A clear fluid that circulates through the lymphatic system carrying immune cells","category":"Tissues & Fluids","difficulty":3,"popularity":65,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"—","definition":"Lymph transports white blood cells and removes interstitial fluid, waste, and pathogens from tissues.","contrast":"Blood","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Tendon',
         '{"description":"A fibrous connective tissue attaching muscle to bone","category":"Tissues & Fluids","difficulty":2,"popularity":70,"group":"Tissues & Fluids","primary_val":"—","secondary_val":"—","definition":"Tendons transmit muscle forces to bones, enabling movement and joint stability through strong collagen fibers.","contrast":"Ligament","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- PLANT BIOLOGY (15)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Photosynthesis',
         '{"description":"The process by which plants convert light energy into chemical energy","category":"Plant Biology","difficulty":1,"popularity":95,"group":"Plant Biology","primary_val":"6CO_2 + 6H_2O → C_6H_12O_6 + 6O_2","secondary_val":"—","definition":"Photosynthesis uses sunlight, water, and carbon dioxide to produce glucose and oxygen in chloroplasts.","formula":"6CO_2 + 6H_2O → C_6H_12O_6 + 6O_2","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Chlorophyll',
         '{"description":"A green pigment in plants that captures light energy for photosynthesis","category":"Plant Biology","difficulty":1,"popularity":90,"group":"Plant Biology","primary_val":"—","secondary_val":"Absorbs red and blue light","definition":"Chlorophyll absorbs sunlight primarily in the blue and red wavelengths, reflecting green light.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Stomata',
         '{"description":"Tiny pores on leaf surfaces that regulate gas exchange and water loss","category":"Plant Biology","difficulty":2,"popularity":80,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Stomata open and close to allow carbon dioxide in and oxygen out while controlling transpiration.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Xylem',
         '{"description":"Vascular tissue that transports water and minerals from roots upward","category":"Plant Biology","difficulty":2,"popularity":80,"group":"Plant Biology","primary_val":"—","secondary_val":"Unidirectional flow","definition":"Xylem consists of hollow tubes that conduct water and dissolved minerals from roots to leaves.","contrast":"Phloem","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Phloem',
         '{"description":"Vascular tissue that transports sugars and nutrients throughout the plant","category":"Plant Biology","difficulty":2,"popularity":80,"group":"Plant Biology","primary_val":"—","secondary_val":"Bidirectional flow","definition":"Phloem distributes the products of photosynthesis from leaves to growing and storage tissues.","contrast":"Xylem","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Root',
         '{"description":"The underground part of a plant that anchors it and absorbs water and minerals","category":"Plant Biology","difficulty":1,"popularity":85,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Roots anchor the plant, absorb water and nutrients from soil, and often store food reserves.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Stem',
         '{"description":"The main structural axis of a plant supporting leaves and flowers","category":"Plant Biology","difficulty":1,"popularity":80,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"The stem provides support, transports fluids between roots and leaves, and may store nutrients.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Leaf',
         '{"description":"The primary photosynthetic organ of a plant","category":"Plant Biology","difficulty":1,"popularity":85,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Leaves are flattened structures specialized for capturing sunlight and performing photosynthesis.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Flower',
         '{"description":"The reproductive structure of angiosperms producing seeds and fruit","category":"Plant Biology","difficulty":1,"popularity":85,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Flowers contain reproductive organs that attract pollinators and develop into fruits containing seeds.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Pollen',
         '{"description":"A fine powdery substance containing male gametes for plant reproduction","category":"Plant Biology","difficulty":2,"popularity":80,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Pollen grains carry sperm cells from the male anther to the female stigma for fertilization.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Seed',
         '{"description":"A mature fertilized plant ovule containing an embryo and stored nutrients","category":"Plant Biology","difficulty":1,"popularity":85,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"A seed protects and nourishes the plant embryo, enabling dispersal and survival until conditions favor germination.","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Fruit',
         '{"description":"The mature ovary of a flower that contains and protects seeds","category":"Plant Biology","difficulty":1,"popularity":85,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Fruits develop from fertilized flowers, aid in seed dispersal, and provide nutrition for animals.","example":"Apples, oranges, berries, tomatoes","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Germination',
         '{"description":"The process by which a seed develops into a new plant","category":"Plant Biology","difficulty":2,"popularity":80,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Germination begins when a seed absorbs water, activates metabolism, and the embryo emerges to grow.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Transpiration',
         '{"description":"The loss of water vapor from plant leaves through stomata","category":"Plant Biology","difficulty":2,"popularity":75,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Transpiration pulls water through the plant from roots to leaves, enabling nutrient transport and cooling.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Tropism',
         '{"description":"A directional growth response of a plant to environmental stimuli","category":"Plant Biology","difficulty":2,"popularity":70,"group":"Plant Biology","primary_val":"—","secondary_val":"—","definition":"Tropism allows plants to grow toward or away from light, gravity, water, or touch for survival.","example":"Phototropism — plants growing toward light","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- MICROBIOLOGY (14)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Bacteria',
         '{"description":"Single-celled prokaryotic microorganisms found in diverse environments","category":"Microbiology","difficulty":1,"popularity":90,"group":"Microbiology","primary_val":"—","secondary_val":"Prokaryotic","definition":"Bacteria are ubiquitous prokaryotes essential for nutrient cycling, digestion, and sometimes causing disease.","contrast":"Virus","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Virus',
         '{"description":"A microscopic infectious agent that replicates only inside living cells","category":"Microbiology","difficulty":1,"popularity":90,"group":"Microbiology","primary_val":"—","secondary_val":"Acellular","definition":"Viruses consist of genetic material enclosed in a protein coat, hijacking host cells for replication.","contrast":"Bacteria","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Fungus',
         '{"description":"A kingdom of eukaryotic organisms including yeasts, molds, and mushrooms","category":"Microbiology","difficulty":2,"popularity":80,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Fungi are heterotrophic eukaryotes that absorb nutrients through external digestion, crucial decomposers.","example":"Mushrooms, yeast, penicillin mold","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Protist',
         '{"description":"A diverse group of mostly unicellular eukaryotic organisms","category":"Microbiology","difficulty":2,"popularity":70,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Protists include algae, amoebas, and paramecia, representing the simplest eukaryotic life forms.","example":"Amoeba, paramecium, euglena","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Archaea',
         '{"description":"Single-celled prokaryotes distinct from bacteria, often thriving in extreme environments","category":"Microbiology","difficulty":3,"popularity":70,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Archaea are ancient microorganisms adapted to extreme heat, salinity, or acidity with unique biochemistry.","example":"Methanogens, thermophiles, halophiles","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Pathogen',
         '{"description":"A microorganism that causes disease in its host","category":"Microbiology","difficulty":2,"popularity":85,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Pathogens include disease-causing bacteria, viruses, fungi, and protists that invade and damage host tissues.","example":"Influenza virus, Salmonella bacteria","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Antibiotic',
         '{"description":"A substance that kills or inhibits the growth of bacteria","category":"Microbiology","difficulty":2,"popularity":90,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Antibiotics target bacterial cell walls, protein synthesis, or DNA replication to treat bacterial infections.","example":"Penicillin, tetracycline, amoxicillin","contrast":"Vaccine","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Vaccine',
         '{"description":"A biological preparation that stimulates immunity against a specific pathogen","category":"Microbiology","difficulty":2,"popularity":90,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Vaccines expose the immune system to harmless antigens, building memory immunity without causing disease.","example":"MMR vaccine, polio vaccine, COVID-19 vaccines","contrast":"Antibiotic","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Bacteriophage',
         '{"description":"A virus that infects and replicates within bacteria","category":"Microbiology","difficulty":3,"popularity":75,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Bacteriophages are viruses specialized in infecting bacteria, used in phage therapy against resistant infections.","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Yeast',
         '{"description":"A single-celled fungus used in baking, brewing, and biotechnology","category":"Microbiology","difficulty":2,"popularity":80,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Yeast ferments sugars into alcohol and carbon dioxide, essential for bread, beer, and wine production.","example":"Saccharomyces cerevisiae (brewer''s yeast)","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Mold',
         '{"description":"A multicellular fungus growing as branching hyphae","category":"Microbiology","difficulty":2,"popularity":75,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Molds decompose organic matter and produce spores for reproduction, with some producing antibiotics.","example":"Penicillium, bread mold, black mold","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Fermentation',
         '{"description":"A metabolic process converting sugars to acids, gases, or alcohol without oxygen","category":"Microbiology","difficulty":2,"popularity":85,"group":"Microbiology","primary_val":"—","secondary_val":"Anaerobic","definition":"Fermentation enables energy production in the absence of oxygen, used in food production and biofuel.","example":"Lactic acid fermentation, alcoholic fermentation","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Decomposition',
         '{"description":"The breakdown of dead organic matter by microorganisms","category":"Microbiology","difficulty":2,"popularity":80,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Decomposition recycles nutrients from dead organisms back into the ecosystem through fungal and bacterial activity.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Biofilm',
         '{"description":"A structured community of microorganisms attached to a surface","category":"Microbiology","difficulty":3,"popularity":70,"group":"Microbiology","primary_val":"—","secondary_val":"—","definition":"Biofilms are microbial communities encased in a protective matrix, resistant to antibiotics and cleaning.","example":"Dental plaque, slime on rocks in streams","images":[]}',
         3, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- MOLECULAR BIOLOGY (14)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Cellular Respiration',
         '{"description":"The process by which cells convert glucose into ATP energy","category":"Molecular Biology","difficulty":2,"popularity":90,"group":"Molecular Biology","primary_val":"C_6H_12O_6 + 6O_2 → 6CO_2 + 6H_2O + ATP","secondary_val":"—","definition":"Cellular respiration breaks down glucose in the presence of oxygen to produce ATP, carbon dioxide, and water.","formula":"C_6H_12O_6 + 6O_2 → 6CO_2 + 6H_2O + ATP","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Glycolysis',
         '{"description":"The first stage of cellular respiration breaking glucose into pyruvate","category":"Molecular Biology","difficulty":3,"popularity":85,"group":"Molecular Biology","primary_val":"Glucose → 2 Pyruvate + 2 ATP","secondary_val":"—","definition":"Glycolysis occurs in the cytoplasm, splitting one glucose molecule into two pyruvates with net ATP production.","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Krebs Cycle',
         '{"description":"A series of chemical reactions generating energy carriers in the mitochondrial matrix","category":"Molecular Biology","difficulty":4,"popularity":80,"group":"Molecular Biology","primary_val":"—","secondary_val":"—","definition":"The Krebs cycle oxidizes acetyl-CoA to produce NADH, FADH_2, and ATP, releasing carbon dioxide.","images":[]}',
         4, ARRAY['concept', 'biology']),
        ('biology', 'Electron Transport Chain',
         '{"description":"A protein complex series that generates ATP through oxidative phosphorylation","category":"Molecular Biology","difficulty":4,"popularity":80,"group":"Molecular Biology","primary_val":"—","secondary_val":"Inner mitochondrial membrane","definition":"The ETC uses electrons from NADH and FADH_2 to pump protons and drive ATP synthase to produce ATP.","images":[]}',
         4, ARRAY['concept', 'biology']),
        ('biology', 'Light Reactions',
         '{"description":"The first stage of photosynthesis converting light energy into ATP and NADPH","category":"Molecular Biology","difficulty":4,"popularity":75,"group":"Molecular Biology","primary_val":"—","secondary_val":"Thylakoid membrane","definition":"Light reactions capture sunlight to split water, releasing oxygen and generating chemical energy carriers.","contrast":"Calvin Cycle","images":[]}',
         4, ARRAY['concept', 'biology']),
        ('biology', 'Calvin Cycle',
         '{"description":"The light-independent stage of photosynthesis fixing carbon into glucose","category":"Molecular Biology","difficulty":4,"popularity":75,"group":"Molecular Biology","primary_val":"—","secondary_val":"Stroma","definition":"The Calvin cycle uses ATP and NADPH from light reactions to convert CO_2 into organic sugars.","contrast":"Light Reactions","images":[]}',
         4, ARRAY['concept', 'biology']),
        ('biology', 'Cell Cycle',
         '{"description":"The ordered series of events leading to cell division","category":"Molecular Biology","difficulty":2,"popularity":85,"group":"Molecular Biology","primary_val":"—","secondary_val":"Interphase + M phase","definition":"The cell cycle includes growth, DNA replication, and division phases that produce two daughter cells.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Mitosis',
         '{"description":"Cell division producing two identical diploid daughter cells","category":"Molecular Biology","difficulty":2,"popularity":90,"group":"Molecular Biology","primary_val":"—","secondary_val":"—","definition":"Mitosis divides the nucleus into two genetically identical nuclei for growth, repair, and asexual reproduction.","contrast":"Meiosis","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Meiosis',
         '{"description":"Cell division producing four genetically unique haploid gametes","category":"Molecular Biology","difficulty":3,"popularity":90,"group":"Molecular Biology","primary_val":"—","secondary_val":"—","definition":"Meiosis reduces chromosome number by half and generates genetic diversity through crossing over and independent assortment.","contrast":"Mitosis","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Apoptosis',
         '{"description":"Programmed cell death that eliminates damaged or unneeded cells","category":"Molecular Biology","difficulty":3,"popularity":80,"group":"Molecular Biology","primary_val":"—","secondary_val":"—","definition":"Apoptosis is a controlled, energy-dependent process of cell suicide essential for development and homeostasis.","contrast":"Necrosis","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Cell Division',
         '{"description":"The process by which a parent cell divides into two or more daughter cells","category":"Molecular Biology","difficulty":2,"popularity":80,"group":"Molecular Biology","primary_val":"—","secondary_val":"—","definition":"Cell division encompasses mitosis for somatic cells and meiosis for gamete production in eukaryotes.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'DNA Repair',
         '{"description":"Cellular mechanisms that correct DNA damage to maintain genome integrity","category":"Molecular Biology","difficulty":4,"popularity":75,"group":"Molecular Biology","primary_val":"—","secondary_val":"—","definition":"DNA repair systems fix mutations, breaks, and mismatches to prevent cancer and maintain genetic stability.","example":"Base excision repair, nucleotide excision repair","images":[]}',
         4, ARRAY['concept', 'biology']),
        ('biology', 'Signal Transduction',
         '{"description":"The process by which cells convert external signals into intracellular responses","category":"Molecular Biology","difficulty":4,"popularity":75,"group":"Molecular Biology","primary_val":"—","secondary_val":"—","definition":"Signal transduction relays messages from receptors through cascades of molecular interactions to cellular outcomes.","example":"Hormone signaling, growth factor pathways","images":[]}',
         4, ARRAY['concept', 'biology']),
        ('biology', 'Gene Expression',
         '{"description":"The process by which information from a gene is used to synthesize functional products","category":"Molecular Biology","difficulty":3,"popularity":85,"group":"Molecular Biology","primary_val":"DNA → RNA → Protein","secondary_val":"—","definition":"Gene expression involves transcription of DNA to RNA and translation of RNA to protein, regulated at multiple levels.","images":[]}',
         3, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- ZOOLOGY (14)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Invertebrate',
         '{"description":"An animal without a backbone or vertebral column","category":"Zoology","difficulty":1,"popularity":85,"group":"Zoology","primary_val":"—","secondary_val":"—","definition":"Invertebrates account for over 95% of animal species, including insects, mollusks, and jellyfish.","contrast":"Vertebrate","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Vertebrate',
         '{"description":"An animal with a backbone or vertebral column","category":"Zoology","difficulty":1,"popularity":85,"group":"Zoology","primary_val":"—","secondary_val":"—","definition":"Vertebrates include fish, amphibians, reptiles, birds, and mammals with an internal skeleton.","contrast":"Invertebrate","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Mammal',
         '{"description":"A warm-blooded vertebrate with hair and mammary glands producing milk","category":"Zoology","difficulty":1,"popularity":90,"group":"Zoology","primary_val":"—","secondary_val":"Warm-blooded","definition":"Mammals nurse their young with milk, have hair or fur, and possess a neocortex for complex behavior.","example":"Humans, whales, bats, dogs","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Reptile',
         '{"description":"A cold-blooded vertebrate with scaly skin that lays amniotic eggs on land","category":"Zoology","difficulty":1,"popularity":80,"group":"Zoology","primary_val":"—","secondary_val":"Cold-blooded","definition":"Reptiles include snakes, lizards, turtles, and crocodiles, covered in scales and breathing with lungs.","contrast":"Amphibian","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Amphibian',
         '{"description":"A cold-blooded vertebrate that lives both in water and on land","category":"Zoology","difficulty":2,"popularity":80,"group":"Zoology","primary_val":"—","secondary_val":"Moist skin","definition":"Amphibians undergo metamorphosis from aquatic larvae to terrestrial adults with permeable skin.","example":"Frogs, salamanders, newts","contrast":"Reptile","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Bird',
         '{"description":"A warm-blooded vertebrate with feathers, wings, and a beak","category":"Zoology","difficulty":1,"popularity":85,"group":"Zoology","primary_val":"—","secondary_val":"Warm-blooded, feathers","definition":"Birds are feathered theropod dinosaurs capable of flight, laying hard-shelled eggs and possessing hollow bones.","example":"Eagles, penguins, sparrows","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Fish',
         '{"description":"An aquatic vertebrate with gills and fins","category":"Zoology","difficulty":1,"popularity":85,"group":"Zoology","primary_val":"—","secondary_val":"Gills and fins","definition":"Fish are aquatic vertebrates ranging from jawless lampreys to bony fish like salmon and clownfish.","example":"Salmon, shark, goldfish","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Arthropod',
         '{"description":"An invertebrate with an exoskeleton, segmented body, and jointed appendages","category":"Zoology","difficulty":2,"popularity":85,"group":"Zoology","primary_val":"—","secondary_val":"Exoskeleton","definition":"Arthropods are the largest animal phylum, including insects, arachnids, crustaceans, and myriapods.","example":"Butterflies, spiders, crabs","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Mollusk',
         '{"description":"A soft-bodied invertebrate often with a hard shell","category":"Zoology","difficulty":2,"popularity":75,"group":"Zoology","primary_val":"—","secondary_val":"—","definition":"Mollusks include snails, clams, octopuses, and squid, characterized by a muscular foot and mantle.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Annelid',
         '{"description":"A segmented worm with a body divided into repeating segments","category":"Zoology","difficulty":2,"popularity":65,"group":"Zoology","primary_val":"—","secondary_val":"Segmented","definition":"Annelids are segmented worms with a complete digestive system and closed circulation.","example":"Earthworms, leeches, bristle worms","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Cnidarian',
         '{"description":"An aquatic invertebrate with stinging cells called cnidocytes","category":"Zoology","difficulty":2,"popularity":70,"group":"Zoology","primary_val":"—","secondary_val":"Stinging cells","definition":"Cnidarians include jellyfish, corals, and sea anemones with radial symmetry and specialized stinging cells.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Porifera',
         '{"description":"The simplest multicellular animals, commonly known as sponges","category":"Zoology","difficulty":2,"popularity":60,"group":"Zoology","primary_val":"—","secondary_val":"—","definition":"Sponges are filter-feeding aquatic animals with porous bodies but no true tissues or organs.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Echinoderm',
         '{"description":"A marine invertebrate with spiny skin and radial symmetry","category":"Zoology","difficulty":2,"popularity":70,"group":"Zoology","primary_val":"—","secondary_val":"Radial symmetry","definition":"Echinoderms such as starfish and sea urchins have a water vascular system for movement and feeding.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Arachnid',
         '{"description":"An arthropod with eight legs, including spiders, scorpions, and ticks","category":"Zoology","difficulty":2,"popularity":75,"group":"Zoology","primary_val":"—","secondary_val":"8 legs","definition":"Arachnids have two body segments and chelicerae for feeding, mostly terrestrial predators.","example":"Spiders, scorpions, mites","contrast":"Insect","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- TAXONOMY & CLASSIFICATION (10)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Taxonomy',
         '{"description":"The science of naming, describing, and classifying organisms","category":"Taxonomy","difficulty":2,"popularity":85,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"Taxonomy organizes life into hierarchical groups based on evolutionary relationships and shared characteristics.","famous_for":"Carl Linnaeus established modern taxonomy","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Binomial Nomenclature',
         '{"description":"The two-part naming system for species using genus and specific epithet","category":"Taxonomy","difficulty":2,"popularity":85,"group":"Taxonomy","primary_val":"Genus species","secondary_val":"—","definition":"Binomial nomenclature assigns each species a unique Latin name consisting of genus and species identifiers.","example":"Homo sapiens for humans, Canis lupus for wolves","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Domain',
         '{"description":"The highest taxonomic rank classifying life into three primary groups","category":"Taxonomy","difficulty":2,"popularity":80,"group":"Taxonomy","primary_val":"—","secondary_val":"3 domains","definition":"The three domains of life are Bacteria, Archaea, and Eukarya, representing the most fundamental divisions.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Kingdom',
         '{"description":"The second-highest taxonomic rank grouping organisms by basic body plan","category":"Taxonomy","difficulty":2,"popularity":80,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"Traditional kingdoms include Animalia, Plantae, Fungi, Protista, and Monera (bacteria).","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Phylum',
         '{"description":"A major taxonomic rank grouping organisms with similar body plans","category":"Taxonomy","difficulty":2,"popularity":75,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"Phylum groups organisms sharing fundamental structural organization within a kingdom.","example":"Chordata (vertebrates), Arthropoda, Mollusca","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Class',
         '{"description":"A taxonomic rank below phylum grouping related orders","category":"Taxonomy","difficulty":2,"popularity":70,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"Class organizes organisms with shared characteristics within a phylum.","example":"Mammalia, Insecta, Aves (birds)","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Order',
         '{"description":"A taxonomic rank grouping related families together","category":"Taxonomy","difficulty":2,"popularity":70,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"Order is a classification level below class, consisting of families that share similar features.","example":"Carnivora, Primates, Rodentia","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Family',
         '{"description":"A taxonomic rank grouping related genera with common ancestry","category":"Taxonomy","difficulty":2,"popularity":65,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"Family groups related genera that share a recent common ancestor and similar characteristics.","example":"Felidae (cats), Hominidae (great apes)","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Genus',
         '{"description":"A taxonomic rank grouping closely related species","category":"Taxonomy","difficulty":2,"popularity":75,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"Genus is a classification level above species, containing species that are closely related and similar.","example":"Homo, Canis, Panthera","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Species',
         '{"description":"The fundamental unit of classification consisting of interbreeding natural populations","category":"Taxonomy","difficulty":2,"popularity":90,"group":"Taxonomy","primary_val":"—","secondary_val":"—","definition":"A species is the largest group of organisms capable of producing fertile offspring under natural conditions.","example":"Homo sapiens, Canis familiaris","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- BOTANY (ADVANCED) (8)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Angiosperm',
         '{"description":"A flowering plant that produces seeds enclosed in fruits","category":"Botany","difficulty":2,"popularity":85,"group":"Botany","primary_val":"—","secondary_val":"Flowering","definition":"Angiosperms are the most diverse plant group, with seeds protected inside ovaries that develop into fruits.","contrast":"Gymnosperm","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Gymnosperm',
         '{"description":"A seed plant with unenclosed or naked seeds, typically on cones","category":"Botany","difficulty":2,"popularity":75,"group":"Botany","primary_val":"—","secondary_val":"Naked seeds","definition":"Gymnosperms include conifers and cycads, with seeds exposed on cone scales rather than enclosed in fruit.","example":"Pine trees, spruce, firs","contrast":"Angiosperm","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Monocot',
         '{"description":"An angiosperm with one cotyledon and parallel leaf veins","category":"Botany","difficulty":2,"popularity":75,"group":"Botany","primary_val":"—","secondary_val":"1 cotyledon","definition":"Monocots have flower parts in multiples of three, fibrous roots, and scattered vascular bundles.","example":"Grasses, lilies, orchids, palms","contrast":"Dicot","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Dicot',
         '{"description":"An angiosperm with two cotyledons and netted leaf veins","category":"Botany","difficulty":2,"popularity":75,"group":"Botany","primary_val":"—","secondary_val":"2 cotyledons","definition":"Dicots have flower parts in multiples of four or five, taproots, and vascular bundles in rings.","example":"Roses, sunflowers, oak trees","contrast":"Monocot","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Evergreen',
         '{"description":"A plant that retains green foliage throughout the year","category":"Botany","difficulty":1,"popularity":75,"group":"Botany","primary_val":"—","secondary_val":"—","definition":"Evergreens keep their leaves across seasons, reducing nutrient loss and extending photosynthesis year-round.","example":"Pine, holly, eucalyptus","contrast":"Deciduous","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Deciduous',
         '{"description":"A plant that sheds its leaves annually in response to seasonal changes","category":"Botany","difficulty":1,"popularity":75,"group":"Botany","primary_val":"—","secondary_val":"—","definition":"Deciduous plants lose leaves in autumn to conserve water and energy during unfavorable seasons.","example":"Maple, oak, birch","contrast":"Evergreen","images":[]}',
         1, ARRAY['concept', 'biology']),
        ('biology', 'Herbaceous',
         '{"description":"A non-woody plant with soft, green stems that die back seasonally","category":"Botany","difficulty":2,"popularity":65,"group":"Botany","primary_val":"—","secondary_val":"Non-woody","definition":"Herbaceous plants have flexible green stems without persistent woody tissue above ground.","example":"Tomatoes, daisies, grasses","contrast":"Woody","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Woody',
         '{"description":"A plant with hard, lignin-reinforced stems that persist above ground","category":"Botany","difficulty":2,"popularity":65,"group":"Botany","primary_val":"—","secondary_val":"Lignified stems","definition":"Woody plants develop bark and secondary xylem, enabling tall growth and perennial survival.","example":"Trees, shrubs, vines","contrast":"Herbaceous","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- IMMUNOLOGY & DISEASE (12)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Antibody',
         '{"description":"A protein produced by the immune system that neutralizes pathogens","category":"Immunology","difficulty":2,"popularity":90,"group":"Immunology","primary_val":"—","secondary_val":"Y-shaped","definition":"Antibodies bind specifically to antigens, marking pathogens for destruction by immune cells.","contrast":"Antigen","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Antigen',
         '{"description":"A molecule recognized by the immune system as foreign, triggering an immune response","category":"Immunology","difficulty":2,"popularity":80,"group":"Immunology","primary_val":"—","secondary_val":"—","definition":"Antigens are typically proteins on pathogen surfaces that stimulate antibody production.","contrast":"Antibody","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Lymphocyte',
         '{"description":"A white blood cell essential for adaptive immune responses","category":"Immunology","difficulty":3,"popularity":80,"group":"Immunology","primary_val":"—","secondary_val":"B and T cells","definition":"Lymphocytes include B cells producing antibodies and T cells killing infected cells or coordinating immunity.","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Inflammation',
         '{"description":"The body''s localized response to tissue injury or infection","category":"Immunology","difficulty":2,"popularity":80,"group":"Immunology","primary_val":"—","secondary_val":"—","definition":"Inflammation increases blood flow and immune cell recruitment to the affected site, causing redness, heat, and swelling.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Active Immunity',
         '{"description":"Immunity acquired through exposure to a pathogen or vaccination","category":"Immunology","difficulty":3,"popularity":75,"group":"Immunology","primary_val":"—","secondary_val":"Long-lasting","definition":"Active immunity develops when the immune system produces its own antibodies after encountering an antigen.","contrast":"Passive Immunity","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Passive Immunity',
         '{"description":"Temporary immunity gained from receiving pre-made antibodies","category":"Immunology","difficulty":3,"popularity":70,"group":"Immunology","primary_val":"—","secondary_val":"Short-lived","definition":"Passive immunity transfers antibodies from another source, providing immediate but temporary protection.","example":"Maternal antibodies to infants through breast milk","contrast":"Active Immunity","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Autoimmune Disease',
         '{"description":"A condition where the immune system mistakenly attacks the body''s own tissues","category":"Immunology","difficulty":3,"popularity":80,"group":"Immunology","primary_val":"—","secondary_val":"—","definition":"Autoimmune diseases occur when self-tolerance fails and immune cells target healthy cells.","example":"Type 1 diabetes, rheumatoid arthritis, lupus","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Allergy',
         '{"description":"An exaggerated immune response to a harmless substance","category":"Immunology","difficulty":2,"popularity":80,"group":"Immunology","primary_val":"—","secondary_val":"—","definition":"Allergies involve hypersensitivity to allergens like pollen, food, or pet dander, triggering histamine release.","example":"Hay fever, peanut allergy, dust mite allergy","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Homeostasis',
         '{"description":"The maintenance of a stable internal environment in the body","category":"Immunology","difficulty":2,"popularity":90,"group":"Immunology","primary_val":"—","secondary_val":"—","definition":"Homeostasis keeps temperature, pH, fluid balance, and other conditions within a narrow optimal range.","example":"Body temperature regulation at ~37°C","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Fever',
         '{"description":"An elevated body temperature as a defensive immune response","category":"Immunology","difficulty":2,"popularity":75,"group":"Immunology","primary_val":"—","secondary_val":">38°C","definition":"Fever enhances immune function by increasing body temperature to inhibit pathogen growth and speed immune responses.","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Phagocyte',
         '{"description":"A white blood cell that engulfs and destroys pathogens and debris","category":"Immunology","difficulty":3,"popularity":70,"group":"Immunology","primary_val":"—","secondary_val":"—","definition":"Phagocytes like macrophages and neutrophils ingest and digest microorganisms and cellular debris.","images":[]}',
         3, ARRAY['concept', 'biology']),
        ('biology', 'Immunoglobulin',
         '{"description":"Another name for antibody, a class of proteins involved in immune defense","category":"Immunology","difficulty":3,"popularity":65,"group":"Immunology","primary_val":"Ig","secondary_val":"5 classes","definition":"Immunoglobulins (IgG, IgA, IgM, IgE, IgD) are antibody proteins with different roles in immunity.","symbol":"Ig","images":[]}',
         3, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- ANIMAL BEHAVIOR (8)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Instinct',
         '{"description":"An innate, fixed pattern of behavior that is genetically programmed","category":"Animal Behavior","difficulty":2,"popularity":80,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Instincts are unlearned behaviors performed the same way by all members of a species.","example":"Spider web spinning, bird nest building","contrast":"Learned Behavior","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Learned Behavior',
         '{"description":"Behavior acquired through experience, observation, or training","category":"Animal Behavior","difficulty":2,"popularity":80,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Learned behaviors are modified by experience and can change over time through conditioning or observation.","example":"Dogs performing tricks, birds learning songs","contrast":"Instinct","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Hibernation',
         '{"description":"A state of inactivity and metabolic depression in animals during winter","category":"Animal Behavior","difficulty":2,"popularity":80,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Hibernation reduces energy consumption during cold months when food is scarce, lowering body temperature and metabolism.","example":"Bears, groundhogs, hedgehogs","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Migration',
         '{"description":"The seasonal movement of animals from one region to another","category":"Animal Behavior","difficulty":2,"popularity":85,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Migration is a regular, often seasonal movement between breeding and feeding grounds for survival.","example":"Monarch butterflies, wildebeest, Arctic terns","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Camouflage',
         '{"description":"The ability to blend with the environment to avoid detection","category":"Animal Behavior","difficulty":2,"popularity":85,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Camouflage uses coloration, pattern, or shape to hide from predators or prey in the natural environment.","example":"Chameleons, Arctic fox, stick insects","contrast":"Mimicry","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Mimicry',
         '{"description":"The resemblance of one organism to another for survival advantage","category":"Animal Behavior","difficulty":2,"popularity":80,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Mimicry involves evolving similar appearance to another species for protection from predators.","example":"Viceroy butterfly mimicking monarch butterfly","contrast":"Camouflage","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Courtship',
         '{"description":"Behavioral displays intended to attract a mate for reproduction","category":"Animal Behavior","difficulty":2,"popularity":75,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Courtship rituals involve songs, dances, or visual displays to demonstrate fitness and secure mating.","example":"Peacock feather display, firefly flashing patterns","images":[]}',
         2, ARRAY['concept', 'biology']),
        ('biology', 'Territorial Behavior',
         '{"description":"The defense of an area against intruders by an animal or group","category":"Animal Behavior","difficulty":2,"popularity":70,"group":"Animal Behavior","primary_val":"—","secondary_val":"—","definition":"Territorial behavior involves marking and defending a geographic area for resources, mating, or nesting.","example":"Wolves howling, birds singing to mark territory","images":[]}',
         2, ARRAY['concept', 'biology']),

        -- ═══════════════════════════════════════════════════════════
        -- FAMOUS BIOLOGISTS (8) — Class A (Persons)
        -- ═══════════════════════════════════════════════════════════
        ('biology', 'Charles Darwin',
         '{"description":"English naturalist who proposed the theory of evolution by natural selection","category":"Biologist","difficulty":2,"popularity":100,"birth_year":1809,"death_year":1882,"nationality":"English","achievement":"Theory of evolution by natural selection","famous_for":"On the Origin of Species and the theory of evolution","definition":"Charles Darwin revolutionized biology by demonstrating that species evolve through natural selection over generations.","images":[]}',
         2, ARRAY['person', 'biology']),
        ('biology', 'Gregor Mendel',
         '{"description":"Austrian monk and scientist who discovered the fundamental laws of inheritance","category":"Biologist","difficulty":2,"popularity":95,"birth_year":1822,"death_year":1884,"nationality":"Austrian","achievement":"Laws of inheritance (Mendelian genetics)","famous_for":"Discovering dominant and recessive traits through pea plant experiments","definition":"Gregor Mendel established the principles of heredity through systematic pea plant breeding experiments.","images":[]}',
         2, ARRAY['person', 'biology']),
        ('biology', 'Louis Pasteur',
         '{"description":"French microbiologist who pioneered germ theory and vaccination","category":"Biologist","difficulty":2,"popularity":95,"birth_year":1822,"death_year":1895,"nationality":"French","achievement":"Germ theory of disease and pasteurization","famous_for":"Pasteurization, rabies vaccine, and disproving spontaneous generation","definition":"Louis Pasteur developed pasteurization, created the first rabies vaccine, and established the germ theory of disease.","images":[]}',
         2, ARRAY['person', 'biology']),
        ('biology', 'Rosalind Franklin',
         '{"description":"English biophysicist whose X-ray crystallography revealed DNA''s double helix structure","category":"Biologist","difficulty":3,"popularity":85,"birth_year":1920,"death_year":1958,"nationality":"English","achievement":"X-ray diffraction images of DNA","famous_for":"Photo 51 — the key evidence for DNA double helix","definition":"Rosalind Franklin''s X-ray crystallography images were crucial evidence for determining the double helix structure of DNA.","images":[]}',
         3, ARRAY['person', 'biology']),
        ('biology', 'Alexander Fleming',
         '{"description":"Scottish physician and microbiologist who discovered penicillin","category":"Biologist","difficulty":2,"popularity":90,"birth_year":1881,"death_year":1955,"nationality":"Scottish","achievement":"Discovery of penicillin","famous_for":"Discovering the first antibiotic — penicillin","definition":"Alexander Fleming discovered that Penicillium mold produced a substance killing bacteria, leading to the first antibiotic.","images":[]}',
         2, ARRAY['person', 'biology']),
        ('biology', 'Jane Goodall',
         '{"description":"English primatologist who revolutionized our understanding of chimpanzee behavior","category":"Biologist","difficulty":2,"popularity":85,"birth_year":1934,"death_year":null,"nationality":"English","achievement":"Groundbreaking chimpanzee behavior research","famous_for":"Decades-long study of wild chimpanzees in Gombe","definition":"Jane Goodall discovered tool use and complex social behaviors in chimpanzees, transforming primatology.","images":[]}',
         2, ARRAY['person', 'biology']),
        ('biology', 'Carl Linnaeus',
         '{"description":"Swedish botanist who created the system of binomial nomenclature","category":"Biologist","difficulty":2,"popularity":85,"birth_year":1707,"death_year":1778,"nationality":"Swedish","achievement":"Binomial nomenclature and classification system","famous_for":"Founder of modern taxonomy — Systema Naturae","definition":"Carl Linnaeus established the system of classifying and naming organisms that biologists still use today.","images":[]}',
         2, ARRAY['person', 'biology']),
        ('biology', 'Robert Hooke',
         '{"description":"English scientist who discovered cells using a microscope","category":"Biologist","difficulty":2,"popularity":80,"birth_year":1635,"death_year":1703,"nationality":"English","achievement":"Discovery of cells and microbial observation","famous_for":"First observation of cells under a microscope","definition":"Robert Hooke''s microscopic observations of cork led to the discovery and naming of cells in biology.","images":[]}',
         2, ARRAY['person', 'biology']);
    END IF;
END $$;
