export const CATEGORIES = [
   {
      id: "mixed",
      name: "Words",
      desc: "Embark on the ultimate vocabulary quest. Decipher anagrams, spot hidden letters, climb word ladders, and test your linguistic reflexes in a high-speed battle of wits.",
      featured: true,
   },

   // Procedural knowledge categories
   {
      id: "maths",
      name: "Mathematics",
      desc: "Enter the calculation chamber. Master rapid arithmetic, solve geometric sequences, tackle algebraic equations, and prove your numerical dominance under pressure.",
   },
   {
      id: "english_language",
      name: "English Language",
      desc: "Vocabulary synonyms, grammar checks, spelling, and literary devices",
   },
   {
      id: "flag_bearer",
      name: "Flags",
      desc: "A global vexillological challenge. Decode national flags, identify country coordinates from color bands, and prove your cartographic memory across all continents.",
      featured: true,
   },
   {
      id: "chemistry",
      name: "Chemistry",
      desc: "Questions about chemistry and chemical elements",
   },
   {
      id: "football",
      name: "Football (Soccer)",
      desc: "Step onto the pitch. Recall legendary World Cup milestones, track active club transfers, identify iconic stadium names, and showcase your tactical soccer knowledge.",
      featured: true,
   },
   {
      id: "sports",
      name: "Sports",
      desc: "General sports trivia including football, basketball, tennis, and olympics",
      //  featured: true,
   },
   {
      id: "geography",
      name: "Geography",
      desc: "World maps, capitals, continents, landmarks, and earth science",
      // featured: true,
   },
   {
      id: "bible",
      name: "Bible",
      desc: "Bible trivia. Test your knowledge of Old and New Testament stories, characters, and verses.",
   },
   {
      id: "global-politics",
      name: "Politics",
      desc: "Global Politics trivia. Test your knowledge of political events and timelines",
   },
   {
      id: "history",
      name: "History",
      desc: "Historical events, ancient civilizations, world wars, and key figures",
      // featured: true,
   },
   {
      id: "general_knowledge",
      name: "General Knowledge",
      desc: "Diverse trivia across pop culture, science, history, and miscellaneous facts",
      // featured: true,
   },
   {
      id: "movies",
      name: "Movies & Cinema",
      desc: "Classic films, blockbusters, actors, directors, and Academy Awards",
      // featured: true,
   },
   {
      id: "television",
      name: "Television",
      desc: "Famous TV series, classic sitcoms, streaming releases, and trivia",
      // featured: true,
   },
   {
      id: "video_games",
      name: "Video Games",
      desc: "Gaming history, console wars, retro arcade, and modern e-sports",
      // featured: true,
   },
   {
      id: "music",
      name: "Music",
      desc: "Popular bands, hit songs, genres, instruments, and music history",
      // featured: true,
   },
   {
      id: "animals",
      name: "Animals & Wildlife",
      desc: "Mammals, birds, reptiles, marine life, and zoological details",
      // featured: true,
   },
   {
      id: "computers",
      name: "Computer Science",
      desc: "Software development, internet history, hardware, coding, and technology",
      // featured: true,
   },
];

export const GRACE_DECAY = 2;

export const FLAG_MAP: Record<string, string> = {
   nigeria: "ng",
   france: "fr",
   germany: "de",
   japan: "jp",
   "united kingdom": "gb",
   "united states": "us",
   canada: "ca",
   brazil: "br",
   australia: "au",
   italy: "it",
   spain: "es",
   china: "cn",
   india: "in",
   mexico: "mx",
   russia: "ru",
   argentina: "ar",
   "south africa": "za",
   "south korea": "kr",
   egypt: "eg",
   netherlands: "nl",
   switzerland: "ch",
   sweden: "se",
   norway: "no",
   turkey: "tr",
   greece: "gr",
   portugal: "pt",
   ireland: "ie",
   "new zealand": "nz",
   ukraine: "ua",
   poland: "pl",
   austria: "at",
   belgium: "be",
   denmark: "dk",
   finland: "fi",
   "saudi arabia": "sa",
   kenya: "ke",
   singapore: "sg",
   vietnam: "vn",
   thailand: "th",
   morocco: "ma",
   colombia: "co",
   peru: "pe",
   chile: "cl",
   pakistan: "pk",
   bangladesh: "bd",
   jamaica: "jm",
   cuba: "cu",
   croatia: "hr",
   hungary: "hu",
   "czech republic": "cz",
   romania: "ro",
   ghana: "gh",
   iceland: "is",
   nepal: "np",
   mongolia: "mn",
   madagascar: "mg",
   "sri lanka": "lk",
   ethiopia: "et",
   bhutan: "bt",
   georgia: "ge",
   philippines: "ph",
   indonesia: "id",
   malaysia: "my",
   israel: "il",
   iran: "ir",
   iraq: "iq",
   serbia: "rs",
   slovakia: "sk",
   slovenia: "si",
   belarus: "by",
   lithuania: "lt",
   latvia: "lv",
   estonia: "ee",
   taiwan: "tw",
   qatar: "qa",
   "united arab emirates": "ae",
   oman: "om",
   kuwait: "kw",
   bahrain: "bh",
   lebanon: "lb",
   jordan: "jo",
   myanmar: "mm",
   cambodia: "kh",
   laos: "la",
   tunisia: "tn",
   algeria: "dz",
   angola: "ao",
   mozambique: "mz",
   zimbabwe: "zw",
   venezuela: "ve",
   uruguay: "uy",
   ecuador: "ec",
   "costa rica": "cr",
   panama: "pa",
   bolivia: "bo",
   paraguay: "py",
   "dominican republic": "do",
   haiti: "ht",
   honduras: "hn",
   "el salvador": "sv",
   guatemala: "gt",
   nicaragua: "ni",
   bahamas: "bs",
   "trinidad and tobago": "tt",
   brunei: "bn",
   fiji: "fj",
   "papua new guinea": "pg",
   cameroon: "cm",
   senegal: "sn",
   "ivory coast": "ci",
   "cote d'ivoire": "ci",
   mali: "ml",
   niger: "ne",
   chad: "td",
   sudan: "sd",
   "south sudan": "ss",
   tanzania: "tz",
   uganda: "ug",
   rwanda: "rw",
   somalia: "so",
   mauritania: "mr",
   "burkina faso": "bf",
   benin: "bj",
   togo: "tg",
   "sierra leone": "sl",
   liberia: "lr",
   zambia: "zm",
   malawi: "mw",
   botswana: "bw",
   namibia: "na",
   lesotho: "ls",
   eswatini: "sz",
   djibouti: "dj",
   eritrea: "er",
   mauritius: "mu",
   seychelles: "sc",
   comoros: "km",
   "cape verde": "cv",
   "equatorial guinea": "gq",
   gabon: "ga",
   "republic of the congo": "cg",
   "democratic republic of the congo": "cd",
   "central african republic": "cf",
   "sao tome and principe": "st",
   "the gambia": "gm",
   guinea: "gn",
   "guinea bissau": "gw",
   afghanistan: "af",
   armenia: "am",
   azerbaijan: "az",
   cyprus: "cy",
   kazakhstan: "kz",
   kyrgyzstan: "kg",
   tajikistan: "tj",
   turkmenistan: "tm",
   uzbekistan: "uz",
   "north korea": "kp",
   maldives: "mv",
   "timor leste": "tl",
   palestine: "ps",
   syria: "sy",
   yemen: "ye",
   albania: "al",
   andorra: "ad",
   "bosnia and herzegovina": "ba",
   bulgaria: "bg",
   monaco: "mc",
   montenegro: "me",
   macedonia: "mk",
   liechtenstein: "li",
   luxembourg: "lu",
   malta: "mt",
   moldova: "md",
   "san marino": "sm",
   "vatican city": "va",
   "holy see": "va",
   kosovo: "xk",
   suriname: "sr",
   guyana: "gy",
   "french guiana": "gf",
   belize: "bz",
   "antigua and barbuda": "ag",
   barbados: "bb",
   dominica: "dm",
   grenada: "gd",
   "st kitts and nevis": "kn",
   "st lucia": "lc",
   "st vincent and the grenadines": "vc",
   samoa: "ws",
   tonga: "to",
   kiribati: "ki",
   tuvalu: "tv",
   vanuatu: "vu",
   "solomon islands": "sb",
   "marshall islands": "mh",
   palau: "pw",
   micronesia: "fm",
   nauru: "nr",
}; // FLAG_MAP
