export const CATEGORIES = [
   {
      id: "mixed",
      name: "Words (Mixed)",
      desc: "All formats, random word lengths",
      featured: true,
   },
   // {
   //    id: "vowel_drop",
   //    name: "Vowel Drop Mode",
   //    desc: "Test word recognition without vowels",
   // },
   // {
   //    id: "anagram_scrambled",
   //    name: "Anagram Scramble",
   //    desc: "Decipher scrambled letters",
   // },
   // {
   //    id: "reverse_wordle",
   //    name: "Reverse Wordle",
   //    desc: "Deduce target words from match grids",
   // },
   // {
   //    id: "missing_letter",
   //    name: "Missing Letters",
   //    desc: "Identify the correct missing letter",
   // },
   // {
   //    id: "word_ladder",
   //    name: "Word Ladder",
   //    desc: "Find words exactly one letter edit away",
   // },
   // {
   //    id: "rhyme_match",
   //    name: "Rhyme Matcher",
   //    desc: "Spot rhyming words programmatically",
   // },
   {
      id: "letter_count",
      name: "Letter Counter",
      desc: "Count vowels or consonants rapidly",
   },
   {
      id: "maths",
      name: "Mathematics",
      desc: "Calculations, geometry puzzles, equations, and mathematical theories",
   },
   {
      id: "english_language",
      name: "English Language",
      desc: "Vocabulary synonyms, grammar checks, spelling, and literary devices",
   },
   // {
   //    id: "english_fundamentals",
   //    name: "English Fundamentals",
   //    desc: "Grammar rules, tenses, punctuation, literary devices, and word usage",
   //    featured: true,
   // },
   // {
   //    id: "currency_exchange",
   //    name: "Currencies",
   //    desc: "Match currencies to their countries",
   // },
   {
      id: "flag_bearer",
      name: "Flags",
      desc: "Identify countries by their flag colors",
      featured: true,
   },
   {
      id: "element_arena",
      name: "Periodic Table",
      desc: "Questions about chemical elements",
   },
   // {
   //    id: "physics",
   //    name: "Physics",
   //    desc: "Mechanics, thermodynamics, waves, optics, electricity, and modern physics",
   //    featured: true,
   // },
   {
      id: "science",
      name: "Science and Nature",
      desc: "General Science",
      featured: true,
   },
   // {
   //    id: "chemistry",
   //    name: "Chemistry",
   //    desc: "Atomic structure, bonding, reactions, organic chemistry, and the periodic table",
   //    featured: true,
   // },
   // {
   //    id: "biology",
   //    name: "Biology",
   //    desc: "Cell biology, genetics, evolution, ecology, anatomy, microbiology, and zoology",
   //    featured: true,
   // },
   // {
   //    id: "football",
   //    name: "Football (Soccer)",
   //    desc: "Players, clubs, competitions, rules, and history of world football",
   //    featured: true,
   // },
   {
      id: "sports",
      name: "Sports",
      desc: "General sports trivia including football, basketball, tennis, and olympics",
   },
   {
      id: "geography",
      name: "Geography",
      desc: "World maps, capitals, continents, landmarks, and earth science",
   },
   {
      id: "history",
      name: "History",
      desc: "Historical events, ancient civilizations, world wars, and key figures",
   },
   {
      id: "general_knowledge",
      name: "General Knowledge",
      desc: "Diverse trivia across pop culture, science, history, and miscellaneous facts",
      featured: true,
   },
   {
      id: "movies",
      name: "Movies & Cinema",
      desc: "Classic films, blockbusters, actors, directors, and Academy Awards",
   },
   {
      id: "television",
      name: "Television",
      desc: "Famous TV series, classic sitcoms, streaming releases, and trivia",
   },
   {
      id: "video_games",
      name: "Video Games",
      desc: "Gaming history, console wars, retro arcade, and modern e-sports",
   },
   {
      id: "music",
      name: "Music",
      desc: "Popular bands, hit songs, genres, instruments, and music history",
   },
   {
      id: "animals",
      name: "Animals & Wildlife",
      desc: "Mammals, birds, reptiles, marine life, and zoological details",
   },
   {
      id: "computers",
      name: "Computer Science",
      desc: "Software development, internet history, hardware, coding, and technology",
   },
];

export const FLAG_MAP: Record<string, string> = {
   nigeria: "ng",
   france: "fr",
   germany: "de",
   japan: "jp",
   "united kingdom": "gb",
   "united states": "us",
   canada: "ca",
   brazil: "br",
   australia: "au",
   italy: "it",
   spain: "es",
   china: "cn",
   india: "in",
   mexico: "mx",
   russia: "ru",
   argentina: "ar",
   "south africa": "za",
   "south korea": "kr",
   egypt: "eg",
   netherlands: "nl",
   switzerland: "ch",
   sweden: "se",
   norway: "no",
   turkey: "tr",
   greece: "gr",
   portugal: "pt",
   ireland: "ie",
   "new zealand": "nz",
   ukraine: "ua",
   poland: "pl",
   austria: "at",
   belgium: "be",
   denmark: "dk",
   finland: "fi",
   "saudi arabia": "sa",
   kenya: "ke",
   singapore: "sg",
   vietnam: "vn",
   thailand: "th",
   morocco: "ma",
   colombia: "co",
   peru: "pe",
   chile: "cl",
   pakistan: "pk",
   bangladesh: "bd",
   jamaica: "jm",
   cuba: "cu",
   croatia: "hr",
   hungary: "hu",
   "czech republic": "cz",
   romania: "ro",
   ghana: "gh",
   iceland: "is",
   nepal: "np",
   mongolia: "mn",
   madagascar: "mg",
   "sri lanka": "lk",
   ethiopia: "et",
   bhutan: "bt",
   georgia: "ge",
   philippines: "ph",
   indonesia: "id",
   malaysia: "my",
   israel: "il",
   iran: "ir",
   iraq: "iq",
   serbia: "rs",
   slovakia: "sk",
   slovenia: "si",
   belarus: "by",
   lithuania: "lt",
   latvia: "lv",
   estonia: "ee",
   taiwan: "tw",
   qatar: "qa",
   "united arab emirates": "ae",
   oman: "om",
   kuwait: "kw",
   bahrain: "bh",
   lebanon: "lb",
   jordan: "jo",
   myanmar: "mm",
   cambodia: "kh",
   laos: "la",
   tunisia: "tn",
   algeria: "dz",
   angola: "ao",
   mozambique: "mz",
   zimbabwe: "zw",
   venezuela: "ve",
   uruguay: "uy",
   ecuador: "ec",
   "costa rica": "cr",
   panama: "pa",
   bolivia: "bo",
   paraguay: "py",
   "dominican republic": "do",
   haiti: "ht",
   honduras: "hn",
   "el salvador": "sv",
   guatemala: "gt",
   nicaragua: "ni",
   bahamas: "bs",
   "trinidad and tobago": "tt",
   brunei: "bn",
   fiji: "fj",
   "papua new guinea": "pg",
   cameroon: "cm",
   senegal: "sn",
   "ivory coast": "ci",
   "cote d'ivoire": "ci",
   mali: "ml",
   niger: "ne",
   chad: "td",
   sudan: "sd",
   "south sudan": "ss",
   tanzania: "tz",
   uganda: "ug",
   rwanda: "rw",
   somalia: "so",
   mauritania: "mr",
   "burkina faso": "bf",
   benin: "bj",
   togo: "tg",
   "sierra leone": "sl",
   liberia: "lr",
   zambia: "zm",
   malawi: "mw",
   botswana: "bw",
   namibia: "na",
   lesotho: "ls",
   eswatini: "sz",
   djibouti: "dj",
   eritrea: "er",
   mauritius: "mu",
   seychelles: "sc",
   comoros: "km",
   "cape verde": "cv",
   "equatorial guinea": "gq",
   gabon: "ga",
   "republic of the congo": "cg",
   "democratic republic of the congo": "cd",
   "central african republic": "cf",
   "sao tome and principe": "st",
   "the gambia": "gm",
   guinea: "gn",
   "guinea bissau": "gw",
   afghanistan: "af",
   armenia: "am",
   azerbaijan: "az",
   cyprus: "cy",
   kazakhstan: "kz",
   kyrgyzstan: "kg",
   tajikistan: "tj",
   turkmenistan: "tm",
   uzbekistan: "uz",
   "north korea": "kp",
   maldives: "mv",
   "timor leste": "tl",
   palestine: "ps",
   syria: "sy",
   yemen: "ye",
   albania: "al",
   andorra: "ad",
   "bosnia and herzegovina": "ba",
   bulgaria: "bg",
   monaco: "mc",
   montenegro: "me",
   macedonia: "mk",
   liechtenstein: "li",
   luxembourg: "lu",
   malta: "mt",
   moldova: "md",
   "san marino": "sm",
   "vatican city": "va",
   "holy see": "va",
   kosovo: "xk",
   suriname: "sr",
   guyana: "gy",
   "french guiana": "gf",
   belize: "bz",
   "antigua and barbuda": "ag",
   barbados: "bb",
   dominica: "dm",
   grenada: "gd",
   "st kitts and nevis": "kn",
   "st lucia": "lc",
   "st vincent and the grenadines": "vc",
   samoa: "ws",
   tonga: "to",
   kiribati: "ki",
   tuvalu: "tv",
   vanuatu: "vu",
   "solomon islands": "sb",
   "marshall islands": "mh",
   palau: "pw",
   micronesia: "fm",
   nauru: "nr",
};
