import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
const ALERT_EMAIL = "cemuchay@gmail.com";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { record } = await req.json();

    if (!record || record.level !== "fatal") {
      return new Response(JSON.stringify({ message: "Not a fatal log, skipping." }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (!RESEND_API_KEY) {
      console.error("RESEND_API_KEY not configured");
      return new Response(JSON.stringify({ error: "Email service not configured" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { message, context, session_id, user_id, created_at } = record;

    const emailResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Wordle Variant Alerts <onboarding@resend.dev>",
        to: [ALERT_EMAIL],
        subject: `🚨 CRITICAL CRASH: ${message}`,
        html: `
          <div style="font-family: sans-serif; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
            <h2 style="color: #e11d48; margin-bottom: 20px;">Critical System Error Detected</h2>
            
            <p><strong>Message:</strong> ${message}</p>
            <p><strong>Log Level:</strong> <span style="background: #fee2e2; color: #991b1b; padding: 2px 6px; border-radius: 4px; font-size: 0.8em; font-weight: bold;">FATAL</span></p>
            <p><strong>Time:</strong> ${new Date(created_at).toLocaleString()}</p>
            <p><strong>Session ID:</strong> <code>${session_id}</code></p>
            <p><strong>User ID:</strong> ${user_id || "Anonymous"}</p>
            
            <h3 style="margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 10px;">Context / Stack Trace</h3>
            <pre style="background: #f8fafc; padding: 15px; border-radius: 8px; overflow-x: auto; font-size: 0.85em;">${JSON.stringify(context, null, 2)}</pre>
            
            <p style="margin-top: 30px; font-size: 0.8em; color: #64748b;">
              This alert was automatically generated by the Client-Side Logger.
            </p>
          </div>
        `,
      }),
    });

    const result = await emailResponse.json();

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
