// -------------------------------------------------------------
// 2. Pre-curated Definitions Database (for Question Type 5)
// -------------------------------------------------------------
const DEFINITIONS: Record<string, string> = {
   AUTHOR: "A person who writes books, stories, or articles.",
   PILOT: "A person who operates the flying controls of an aircraft.",
   DOCTOR: "A qualified practitioner of medicine; a physician.",
   POET: "A person who writes poems.",
   COMPUTER: "An electronic device for storing and processing data.",
   OCEAN: "A very large expanse of sea, in particular, each of the main areas of saline water.",
   ELEPHANT:
      "A very large plant-eating mammal with a prehensile trunk and long ivory tusks.",
   GUITAR:
      "A stringed musical instrument, with six or twelve strings, played by plucking or strumming.",
   ASTRONAUT: "A person who is trained to travel in a spacecraft.",
   BAKER: "A person who makes and sells bread, cake, and pastry.",
   TEACHER:
      "A person who helps students to acquire knowledge, competence, or virtue.",
   LIBRARY:
      "A building or room containing collections of books, periodicals, and sometimes films.",
   MOUNTAIN:
      "A large natural elevation of the earth's surface rising abruptly from the surrounding level.",
   VOLCANO:
      "A mountain or hill, typically conical, having a crater or vent through which lava, rock fragments, hot vapor, and gas are or have been erupted from the earth's crust.",
   JOURNALIST:
      "A person who writes for newspapers, magazines, or news websites or prepares news to be broadcast.",
   CHEMIST:
      "An expert in chemistry, or a person engaged in chemical research or experiments.",
   SCIENTIST:
      "A person who is studying or has expert knowledge of one or more of the natural or physical sciences.",
   SOLDIER: "A person who serves in an army.",
   DENTIST:
      "A person qualified to treat the diseases and other conditions that affect the teeth and gums.",
   ENGINEER:
      "A person who designs, builds, or maintains engines, machines, or public works.",
   FIREMAN: "A person whose job is to extinguish fires.",
   LAWYER: "A person who practices or studies law; an attorney or counselor.",
   ARTIST:
      "A person who creates paintings or drawings as a profession or hobby.",
   ACTOR: "A person whose profession is acting on the stage, in films, or on television.",
   MUSICIAN:
      "A person who plays a musical instrument, especially as a profession, or is musically talented.",
   FARMER: "A person who owns or manages a farm.",
   CHEF: "A professional cook, typically the chief cook in a restaurant or hotel.",
   WAITER:
      "A man whose job is to serve customers at their tables in a restaurant.",
   NURSE: "A person trained to care for the sick or infirm, especially in a hospital.",
   POLICE:
      "The civil force of a state or municipal government, responsible for the prevention and detection of crime.",
   BREAD: "Food made of flour, water, and yeast mixed together and baked.",
   CHEESE: "A food made from the pressed curds of milk.",
   APPLE: "The round fruit of a tree of the rose family, which typically has thin green or red skin and crisp white flesh.",
   BANANA:
      "A long curved fruit which grows in clusters and has soft pulpy flesh and yellow skin.",
   COFFEE:
      "A hot drink made from the roasted and ground seeds (coffee beans) of a tropical shrub.",
   CHICKEN: "A domestic fowl kept for its eggs or meat.",
   SCHOOL: "An institution for educating children.",
   CAMERA:
      "A device for recording visual images in the form of photographs, film, or video signals.",
   TELEPHONE:
      "A system for transmitting voices over a distance using wire or radio.",
   BICYCLE:
      "A vehicle consisting of two wheels held in a frame one behind the other, propelled by pedals.",
   JOLLOF: "A rice dish cooked with tomatoes, peppers, onions, and spices.",
   PLANTAIN:
      "A starchy fruit similar to a banana, usually cooked before eating.",
   YAM: "A starchy edible tuber cultivated in tropical regions.",
   CASSAVA: "A tropical shrub cultivated for its edible starchy root.",
   OKRA: "A flowering plant cultivated for its edible green seed pods.",
   PEPPER: "The pungent fruit of various plants used as a spice or vegetable.",
   PALMOIL: "Edible oil extracted from the fruit of oil palm trees.",
   GROUNDNUT: "Another name for the peanut, an edible legume.",
   MOIMOI: "A steamed pudding made from ground beans and spices.",
   AKARA: "Deep-fried bean cakes made from peeled beans.",
   SUYA: "Spiced grilled meat prepared on skewers.",
   GARAGE: "A place where buses and taxis gather to pick up passengers.",
   MARKET: "A place where people buy and sell goods.",
   MOSQUE: "A place of worship for Muslims.",
   CHURCH: "A building used for Christian worship.",
   CAMPUS: "The grounds and buildings of a university or college.",
   HOSTEL:
      "A place providing inexpensive accommodation for students or travelers.",
   LECTURER: "A person who teaches at a university or college.",
   STUDENT: "A person who is studying at a school or university.",
   PREFECT: "A student appointed to maintain order or supervise others.",
   UNIFORM:
      "Distinctive clothing worn by members of the same organization or school.",
   KIOSK: "A small booth or shop selling goods.",
   TAILOR: "A person who makes or alters clothes.",
   BARBER: "A person who cuts and styles hair.",
   MECHANIC: "A person skilled in repairing machinery or vehicles.",
   TRADER: "A person who buys and sells goods.",
   VENDOR: "A person offering goods for sale.",
   BANKER: "A person employed by a bank.",
   ACCOUNTANT: "A person who keeps or inspects financial accounts.",
   CLERK: "An office worker responsible for records or administrative tasks.",
   PHARMACY: "A shop or department where medicines are dispensed.",
   HOSPITAL: "An institution providing medical treatment and care.",
   AMBULANCE: "A vehicle equipped for transporting sick or injured people.",
   TRAFFIC: "Vehicles moving along roads or highways.",
   HIGHWAY: "A main road, especially one connecting major towns or cities.",
   BRIDGE: "A structure built to span a river, road, or obstacle.",
   AIRPORT: "A complex where aircraft take off and land.",
   RUNWAY: "A strip of ground where aircraft take off and land.",
   PASSPORT: "An official document identifying a citizen traveling abroad.",
   VILLAGE: "A group of houses and associated buildings in a rural area.",
   CAPITAL:
      "The city that serves as the seat of government of a country or state.",
   LAGOON: "A stretch of salt water separated from the sea by a barrier.",
   RAINFALL: "The amount of rain that falls in a particular area.",
   SUNSHINE: "Direct light and heat from the sun.",
   HARMATTAN: "A dry, dusty seasonal wind that blows across West Africa.",
   GENERATOR: "A machine that produces electricity.",
   ELECTRIC: "Powered by or producing electricity.",
   BATTERY: "A device that stores and supplies electrical energy.",
   CHARGER: "A device used to recharge a battery.",
   INTERNET:
      "A global computer network providing information and communication.",
   KEYBOARD: "A panel of keys used to operate a computer.",
   MONITOR: "A screen used to display computer output.",
   PRINTER: "A machine that produces text or images on paper.",
   NOTEBOOK: "A book of blank pages for writing notes.",
   BACKPACK: "A bag carried on the back using shoulder straps.",
   UMBRELLA: "A device used for protection against rain or sunlight.",
   SANDALS: "Open shoes fastened by straps.",
   SLIPPERS: "Light footwear easily slipped on and off.",
   CEMENT: "A binding material used in construction.",
   BUILDING: "A permanent structure with walls and a roof.",
   LANDLORD: "A person who rents property to others.",
   TENANT: "A person who occupies rented property.",
   NEIGHBOR: "A person living near another.",
   COMMUNITY:
      "A group of people living in the same place or sharing common interests.",
   FESTIVAL: "An organized celebration or series of events.",
   MARRIAGE: "The legally recognized union of two people as partners.",
   BIRTHDAY: "The anniversary of the day on which a person was born.",
   HOLIDAY: "A day set aside for celebration or recreation.",
   FAMILY: "A group consisting of parents and their children.",
   COUSIN: "A child of one's aunt or uncle.",
   UNCLE: "The brother of one's parent or the husband of one's aunt.",
   AUNT: "The sister of one's parent or the wife of one's uncle.",
   GRANDMOTHER: "The mother of one's father or mother.",
   GRANDFATHER: "The father of one's father or mother.",
   ABACUS: "A frame with beads used for counting and arithmetic.",
   ACCOUNT: "A record or statement of financial transactions.",
   AIRLINE: "A company that provides air transport services.",
   ALMANAC: "An annual publication containing useful facts and statistics.",
   ANCHOR: "A heavy object used to keep a ship from drifting.",
   APRON: "A protective garment worn over clothing.",
   ARCHIVE: "A collection of historical documents or records.",
   ATHLETE: "A person trained in sports or physical exercise.",
   BALANCE: "A state in which different elements are equal or stable.",
   BALLOON:
      "A flexible bag filled with gas, often used for decoration or flight.",
   BANKING: "The business of managing money and financial services.",
   BASKET: "A container made of woven material used for carrying items.",
   BEVERAGE: "A drink other than water.",
   BLACKBOARD: "A dark board used for writing with chalk.",
   BLANKET: "A large piece of cloth used for warmth.",
   BOOKLET: "A small book with a paper cover.",
   BOTTLE: "A container with a narrow neck used for liquids.",
   BRICK: "A rectangular block used in building construction.",
   BROCHURE: "A small booklet used for advertising or information.",
   BROOM: "A cleaning tool made of stiff fibers attached to a handle.",
   BUCKET: "A round container used for carrying liquids or materials.",
   BULB: "The glass part of an electric lamp that produces light.",
   CABINET: "A cupboard or storage unit with shelves or drawers.",
   CALENDAR: "A chart showing the days, weeks, and months of the year.",
   CAPTAIN: "The person in command of a ship, aircraft, or team.",
   CARPENTER: "A person skilled in working with wood.",
   CARPET: "A thick woven floor covering.",
   CASHIER: "A person who receives payments in a shop or bank.",
   CATTLE: "Large farm animals raised for meat or milk.",
   CEILING: "The overhead interior surface of a room.",
   CELLAR: "An underground storage room.",
   CEREMONY: "A formal event performed on a special occasion.",
   CHARITY: "The voluntary giving of help to those in need.",
   CHECKUP: "A routine medical examination.",
   CHIMNEY: "A vertical passage through which smoke escapes.",
   CITIZEN: "A legally recognized member of a country.",
   CLASSROOM: "A room where teaching takes place.",
   CLIMATE: "The usual weather conditions of an area.",
   CLINIC: "A healthcare facility for outpatient treatment.",
   COLLEGE: "An institution of higher education.",
   COMPASS: "An instrument used for navigation and direction.",
   CONDUCTOR:
      "A person who collects fares on public transport or leads musicians.",
   CONTRACT: "A legally binding agreement.",
   COOKING: "The process of preparing food by heating.",
   COTTON: "A soft fiber obtained from the cotton plant.",
   COURT: "A place where legal cases are heard.",
   CULTURE: "The customs and traditions of a society.",
   CURTAIN: "A piece of fabric hung to cover a window.",
   CUSTOMER: "A person who buys goods or services.",
   CYCLIST: "A person who rides a bicycle.",
   DAIRY: "Food made from milk or a place where milk products are processed.",
   DANGER: "The possibility of harm or injury.",
   DELIVERY: "The act of transporting goods to a destination.",
   DESERT: "A dry region with little rainfall.",
   DIAMOND: "A precious gemstone made of crystallized carbon.",
   DINNER: "The main meal of the day.",
   DIPLOMA: "A certificate awarded after completing a course of study.",
   DISCOUNT: "A reduction in price.",
   DONATION: "Something given to help a person or cause.",
   DRIVER: "A person who operates a motor vehicle.",
   DROUGHT: "A prolonged period of unusually low rainfall.",
   ECLIPSE:
      "The partial or complete blocking of one celestial body by another.",
   ECONOMY: "The system of production and consumption in a country.",
   EDITION: "A particular version of a published work.",
   ELECTION: "The process of choosing leaders by voting.",
   EMBASSY: "The official residence or offices of an ambassador.",
   EMERGENCY: "A serious situation requiring immediate action.",
   EMPLOYEE: "A person who works for wages or salary.",
   ENTRANCE: "A place or way of entering.",
   ENVELOPE: "A paper cover for a letter.",
   EXAMINE: "To inspect or study carefully.",
   FACTORY: "A building where goods are manufactured.",
   FARMHOUSE: "The main house on a farm.",
   FASHION: "A popular style of dress or behavior.",
   FEATHER: "One of the soft growths covering a bird.",
   FERTILE: "Capable of producing abundant crops or offspring.",
   FINANCE: "The management of money and investments.",
   FISHERMAN: "A person who catches fish.",
   FOOTBALL: "A game played by two teams aiming to score goals with a ball.",
   FOUNTAIN: "A structure that sends water into the air.",
   FURNITURE: "Movable objects such as tables and chairs used in a home.",
   GARDENER: "A person who grows and cares for plants.",
   GASOLINE: "Fuel used in internal combustion engines.",
   GLASSES: "Lenses worn to improve vision.",
   GROCERY: "A shop selling food and household items.",
   HANDSHAKE: "A greeting in which two people clasp hands.",
   HARVEST: "The process of gathering mature crops.",
   HEADMASTER: "The principal of a school.",
   HEADMISTRESS: "The female principal of a school.",
   HELMET: "Protective headgear.",
   HIGHLAND: "An area of elevated land.",
   HOLSTER: "A holder for carrying a tool or weapon.",
   HUNTER: "A person who hunts animals.",
   ICEBERG: "A large floating mass of ice.",
   INVOICE: "A document requesting payment for goods or services.",
   JACKET: "A short coat worn on the upper body.",
   JANITOR: "A person responsible for cleaning and maintaining a building.",
   JEWELRY: "Decorative items worn for personal adornment.",
   JOURNEY: "An act of traveling from one place to another.",
   JUSTICE: "Fair treatment according to law.",
};

// -------------------------------------------------------------
// 2b. Thematic Groups (for synonym_match + category_sort)
// -------------------------------------------------------------
const THEME_GROUPS: Record<string, string[]> = {
   MEDICAL: [
      "DOCTOR", "NURSE", "DENTIST", "CHEMIST", "HOSPITAL", "CLINIC", "PHARMACY", "AMBULANCE",
   ],
   EDUCATION: [
      "TEACHER", "STUDENT", "LECTURER", "HEADMASTER", "SCHOOL", "COLLEGE", "CLASSROOM", "CAMPUS", "LIBRARY", "NOTEBOOK",
   ],
   FOOD: [
      "BREAD", "CHEESE", "APPLE", "BANANA", "COFFEE", "CHICKEN", "BAKER", "CHEF", "WAITER", "GROCERY",
      "YAM", "CASSAVA", "OKRA", "PEPPER", "JOLLOF", "PLANTAIN", "MOIMOI", "AKARA", "SUYA",
   ],
   TRANSPORT: [
      "PILOT", "DRIVER", "CAPTAIN", "BICYCLE", "AIRPORT", "RUNWAY", "AIRLINE", "HIGHWAY", "BRIDGE", "TRAFFIC",
   ],
   CREATIVE: ["AUTHOR", "POET", "ARTIST", "MUSICIAN", "ACTOR", "JOURNALIST"],
   JUSTICE: ["LAWYER", "POLICE", "COURT", "JUSTICE", "CONTRACT"],
   NATURE: [
      "OCEAN", "MOUNTAIN", "VOLCANO", "DESERT", "LAGOON", "SUNSHINE", "RAINFALL", "CLIMATE", "DROUGHT", "ECLIPSE", "ICEBERG",
   ],
   CLOTHING: [
      "UNIFORM", "SANDALS", "SLIPPERS", "APRON", "JACKET", "HELMET", "GLASSES", "JEWELRY",
   ],
   TECHNOLOGY: [
      "COMPUTER", "KEYBOARD", "MONITOR", "PRINTER", "INTERNET", "CAMERA", "TELEPHONE", "BATTERY", "CHARGER", "GENERATOR",
   ],
   FINANCE: [
      "BANKER", "ACCOUNTANT", "CASHIER", "BANKING", "FINANCE", "INVOICE",
   ],
   HOME: [
      "FAMILY", "COUSIN", "UNCLE", "AUNT", "GRANDMOTHER", "GRANDFATHER", "NEIGHBOR", "LANDLORD", "TENANT", "FURNITURE",
   ],
   BUILDING: [
      "SCHOOL", "HOSPITAL", "CHURCH", "MOSQUE", "LIBRARY", "AIRPORT", "FACTORY", "GARAGE", "HOSTEL", "KIOSK", "MARKET",
   ],
   SPORTS: ["FOOTBALL", "ATHLETE", "CYCLIST", "BASKET", "BALLOON"],
   PROFESSION: [
      "DOCTOR", "NURSE", "TEACHER", "LAWYER", "ENGINEER", "SCIENTIST", "ARTIST", "MUSICIAN", "ACTOR",
      "PILOT", "CAPTAIN", "CARPENTER", "MECHANIC", "TAILOR", "BARBER", "FARMER", "BAKER", "CHEF",
      "JANITOR", "HUNTER", "FISHERMAN", "GARDENER", "SOLDIER", "FIREMAN", "CLERK",
   ],
};

// -------------------------------------------------------------
// 2c. Compound Words Database (for compound_break)
// -------------------------------------------------------------
const COMPOUND_PARTS: [string, string, string][] = [
   ["NOTEBOOK", "NOTE", "BOOK"],
   ["SUNFLOWER", "SUN", "FLOWER"],
   ["BIRTHDAY", "BIRTH", "DAY"],
   ["FOOTBALL", "FOOT", "BALL"],
   ["HIGHLAND", "HIGH", "LAND"],
   ["RAINFALL", "RAIN", "FALL"],
   ["SUNSHINE", "SUN", "SHINE"],
   ["CLASSROOM", "CLASS", "ROOM"],
   ["BLACKBOARD", "BLACK", "BOARD"],
   ["HEADMASTER", "HEAD", "MASTER"],
   ["AIRPORT", "AIR", "PORT"],
   ["KEYBOARD", "KEY", "BOARD"],
   ["BACKPACK", "BACK", "PACK"],
   ["FARMHOUSE", "FARM", "HOUSE"],
   ["BASKETBALL", "BASKET", "BALL"],
   ["EARTHQUAKE", "EARTH", "QUAKE"],
   ["WORKSHOP", "WORK", "SHOP"],
   ["PASSPORT", "PASS", "PORT"],
   ["RAINBOW", "RAIN", "BOW"],
   ["SAILBOAT", "SAIL", "BOAT"],
   ["SNOWBALL", "SNOW", "BALL"],
   ["STARFISH", "STAR", "FISH"],
   ["SUNSET", "SUN", "SET"],
   ["TOOTHBRUSH", "TOOTH", "BRUSH"],
   ["WATERFALL", "WATER", "FALL"],
   ["WATERMELON", "WATER", "MELON"],
   ["WRISTWATCH", "WRIST", "WATCH"],
   ["DOORSTEP", "DOOR", "STEP"],
   ["HONEYMOON", "HONEY", "MOON"],
   ["PANCAKE", "PAN", "CAKE"],
   ["PINEAPPLE", "PINE", "APPLE"],
   ["PLAYGROUND", "PLAY", "GROUND"],
   ["POPCORN", "POP", "CORN"],
   ["SIDEWALK", "SIDE", "WALK"],
   ["SPACESHIP", "SPACE", "SHIP"],
   ["LIGHTHOUSE", "LIGHT", "HOUSE"],
   ["LAWNMOWER", "LAWN", "MOWER"],
   ["NIGHTMARE", "NIGHT", "MARE"],
   ["LIPSTICK", "LIP", "STICK"],
   ["LIFEGUARD", "LIFE", "GUARD"],
   ["UNDERWEAR", "UNDER", "WEAR"],
];

export { DEFINITIONS, THEME_GROUPS, COMPOUND_PARTS };
